### ISSUE TITLE
Birt Run time 4.9.0 with JDk11 giving issues on GCP

### ISSUE THREAD

**Issue by ripjal** [eclipse/birt#1016]
We have recently upgraded our product to use JDK11 and 4.9.0,after overcoming several issues we were able to run BIRT in our web application on our local Windows and Mac Environment. But when we are deploying the same web application to our Google Cloud environment , system is not able to create ReportEngineFactory due to NPE

We use below line of code to instantiate ReportEngineFactory
`			IReportEngineFactory factory = (IReportEngineFactory) Platform.createFactoryObject(IReportEngineFactory.EXTENSION_REPORT_ENGINE_FACTORY);`

Internally Platform.createFactoryObject throws NPE due to platform being NULL.It has been hard to debug as there are barely any logs in eclipse birt and locally not reproduceable as well
Any help or insight is much appreciated

Our Google environment is based Centos OS and we use CloudSQl Postgres service

**Comment by wimjongman** [comment]
This issue has been solved in 4.10

Please test our new release candidate available here: https://download.eclipse.org/birt/downloads/drops/snapshot/
