### ISSUE TITLE
Excel error with large number of rows/groups

### ISSUE THREAD

**Issue by ltuch** [eclipse/birt#1038]
I have a report with a large number of rows (18585) and a large number of groups (482).

Using the BIRT viewer I am able to generate a report using the XLSX emitter. However, when I open it Excel (2016) indicates there is a problem opening the file and it gives me a recovery option. When I select the recovery option it then gives me the following message:

```
Excel completed file level validation and repair. Some part of the workbook may have been repaired or discarded. 
Removed records: Named range from /xl/workbook.xml part (Workbook)
```

If I look inside the `/xl/workbook.xml` file I can see that it has a very long named expression. Please see [here](https://github.com/eclipse/birt/files/9430511/workbook.xml.txt).

When generating smaller reports, with fewer rows/groups I do not see this error, so I suspect the issue is to do with the the large number of rows/groups, and building the named expression for the grouping.

As a temporary workaround for the issue I removed the code inside the `uk.co.spudsoft.birt.emitters.excel.handlers.AbstractHandler.createName` method. This enabled me to run my large report without any errors from Excel.

**Comment by hvbtup** [comment]
Correct my if I'm wrong but it seems that in your special case the cells making up the name are a structure like this:

    xx
    xx
       xx
       xx
          xx
          xx

... and so on

It's not the *name* which is long, it's the cell range defined by the name.
A structure like this cannot be simplified (which was my first thought).

Next thought: Instead of just removing all the code inside the `createName` method, maybe you can use a UserProperty to decide wether to call skip the code or not.

By looking at the places from where `createName` is called, it seems like it is only called if a cell (or row, group, whatever) has a bookmark.

So it should be possible to easily avoid calls to `createName` if you just don't use bookmarks in your report.

Note that the bookmarks are Javascript expressions.
I don't know for sure if a `null` or `undefined` bookmark is treated like no bookmark at all, but you can test that of course. Given that's the case, you could use any condition you like in your report to avoid bookmarks for the huge reports.

**Comment by ltuch** [comment]
Regarding the bookmarks, In my test there were no explicitly defined bookmarks. On the grouping itself there was no defined bookmark and neither were there any bookmarks defined elsewhere in the report.

I also experimented by setting the bookmark on the group to `null` or `undefined` (instead of no value) and that didn't seem to help.

It seems to me that when I added the grouping to the report it implicitly added a bookmark into the report. I'm guessing a little bit here.

**Comment by hvbtup** [comment]
Just to be clear: So you *.rptdesign XML source (and *.rptlibrary XML, if used) does not contain any `<bookmark` text?

**Comment by ltuch** [comment]
Yes, that is correct. They do not contain any `<bookmark>` elements.

I can see some references to a toc. For example there is one in the group header which looks like `<structure name="toc"/>`. But I don't know if that would be causing any issues.

**Comment by ltuch** [comment]
I actually managed to reproduce the issue on a simplified report which does not do any grouping.

The attached [report](https://github.com/eclipse/birt/files/9431122/test7.rptdesign.txt) uses data from the ClassicModels database. The Data Set query is a bit silly, but I was just looking for something simple to reproduce the issue.

**Comment by hvbtup** [comment]
Yes! That's it!
The TOC entries are also bookmarks and they are causing this issue.
TOC entries are generated automatically. To avoid creating TOC entries, you have to clear the corresponding field in the group editor dialog.

**Comment by ltuch** [comment]
> I actually managed to reproduce the issue on a simplified report which does not do any grouping.
> 
> The attached [report](https://github.com/eclipse/birt/files/9431122/test7.rptdesign.txt) uses data from the ClassicModels database. The Data Set query is a bit silly, but I was just looking for something simple to reproduce the issue.

I just found that If I modify this report to use an Auto Layout and disable page breaks then the error goes away.

Also, with my original report (which uses grouping), if I disable page breaks on the group, then the Excel error also goes away too.

What I'm trying to achieve is have a report which uses groups, where each group is displayed on a separate page. It seems that when I'm using page breaks, this causes Birt to automatically add each page into the named range which causes issues when there are large number of groups/page breaks.

**Comment by lauriekoorong** [comment]
I think I found a workaround which does not involve modifying the BIRT emitter code.

Earlier I tried setting the group bookmark expression to `null` to no avail.

This time I set the table bookmark expression to `null` and this appears to have addressed the issue! When the table bookmark expression is set to `null` then no named ranges are created in the `workbook.xml` file.

**Comment by ltuch** [comment]
I think I found a workaround which does not involve modifying the BIRT emitter code.

Earlier I tried setting the group bookmark expression to null to no avail.

This time I set the table bookmark expression to null and this appears to have addressed the issue! When the table bookmark expression is set to null then no named ranges are created in the workbook.xml file.

**Comment by hvbtup** [comment]
I'll close this issue then.
