### ISSUE TITLE
Build for 4.10 fails

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#1049]
```
 Error:  Failed to resolve target definition /home/runner/work/birt/birt/build/org.eclipse.birt.target/org.eclipse.birt.target.target: 
      Failed to load p2 metadata repository from location https://download.eclipse.org/webtools/repository/latest/: 
      Unable to read repository at https://download.eclipse.org/webtools/repository/latest. 
      No repository found at https://download.eclipse.org/webtools/repository/latest/releases. -> [Help 1]

```

**Comment by wimjongman** [comment]
It is good that I upgraded to 4.25. We were using removed API.

Now I am stuck here. Does anyone know how to solve it?

[INFO] org.eclipse.birt.report.designer.ui.preview.test 4.10.0-SNAPSHOT SKIPPED
[INFO] org.eclipse.birt.UI-parent 4.10.0-SNAPSHOT ......... SKIPPED
[INFO] org.eclipse.birt.jetty.overlay 4.10.0-SNAPSHOT ..... SKIPPED
[INFO] org.eclipse.birt.report.viewer.tests 4.10.0-SNAPSHOT SKIPPED
[INFO] org.eclipse.birt.viewer-parent 4.10.0-SNAPSHOT ..... SKIPPED
[INFO] org.eclipse.birt.report.item.crosstab.core.tests 4.10.0-SNAPSHOT SKIPPED
[INFO] org.eclipse.birt.xtab-parent 4.10.0-SNAPSHOT ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:53 min
[INFO] Finished at: 2022-09-19T23:49:08+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:compile (default-compile) on project org.eclipse.birt.core.ui: Compilation failure: Compilation failure:
[ERROR] C:\Apps\eclipse\oomph\birt-master\git\birt\core\org.eclipse.birt.core.ui\src\org\eclipse\birt\core\ui\frameworks\taskwizard\SequencedTask.java:[26]
[ERROR]         import com.ibm.icu.util.ULocale;
[ERROR]                ^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Access restriction: The type 'ULocale' is not API (restriction on classpath entry 'C:\Users\jongw\.m2\repository\com\ibm\icu\icu4j\70.1\icu4j-70.1.jar')
[ERROR] C:\Apps\eclipse\oomph\birt-master\git\birt\core\org.eclipse.birt.core.ui\src\org\eclipse\birt\core\ui\frameworks\taskwizard\SequencedTask.java:[56]
[ERROR]         public String getDisplayLabel(ULocale locale) {
[ERROR]                                       ^^^^^^^
[ERROR] Access restriction: The type 'ULocale' is not API (restriction on classpath entry 'C:\Users\jongw\.m2\repository\com\ibm\icu\icu4j\70.1\icu4j-70.1.jar')
[ERROR] C:\Apps\eclipse\oomph\birt-master\git\birt\core\org.eclipse.birt.core.ui\src\org\eclipse\birt\core\ui\frameworks\taskwizard\SequencedTask.java:[132]
[ERROR]         public String getDescription(ULocale locale) {
[ERROR]                                      ^^^^^^^
[ERROR] Access restriction: The type 'ULocale' is not API (restriction on classpath entry 'C:\Users\jongw\.m2\repository\com\ibm\icu\icu4j\70.1\icu4j-70.1.jar')

**Comment by claesrosell** [comment]
According to this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=562582 ICU support in Eclipse should be removed with the 2022-06, release. So the time seems right for this error to appear. 

I am not at all familiar with ICU, but to my understanding com.ibm.icu.util.ULocale is the "enhanced version" of java.util.Locale . The error message "Access restriction: The type 'ULocale' is not API" seems strange since ULocale probably is API, from ICU's perspective. The visibility of the packages must have been altered with the latest version of the platform.

A search for "import com.ibm.icu" in the Birt workspace produces 985 matches.  Some migration to core java can probably be automated, but it is still a big job.

**Comment by hvbtup** [comment]
Same semi-knowledge here: ICU is an enhancement for Java's builtin I18N capabilities.

A possible way to handle this could be:

As a first step, remove all import `com.ibm.icu...` statements from the source code and remove the ICU library.

Then work like this: search for ULocale, add an import java.util.Locale to these files and replace ULocale with Locale.

And so on for other classes - for most if not all of them there should be a corresponding class in Java's builtin libraries.

Hopefully there will be only few cases where such an exact replacement is not possible, or none at all.

That should make the build process work with some effort.

If every edge case actually works like before, that's a different question, see for example the comment in the bug Claes mentioned.

**Comment by claesrosell** [comment]
It looks like we are pulling ICU from maven, so my initial guess that the visibility of ULocale had been changed in the Eclipse Platform is probably wrong. 

I also see that the format for maven dependencies in target platform files has changed some. Do we need to update Tycho as well? 

Looking in the PDE, the "org.eclipse.birt.core.ui" actually doesn´t have access to com.ibm.icu.util seems strange that this has worked earlier.

![bild](https://user-images.githubusercontent.com/8941815/191232798-b4903077-20c7-4929-9c9c-96c6e66bd079.png)

**Comment by wimjongman** [comment]
The wiring is gone mad a bit. BIRT is very fond of re-exporting dependencies (which I hate).

org.eclipse.birt.core.ui imports icu in the package imports but it already gets the import from birt.core which re-exports icu. Simply removing the re-export causes a lot of errors.

**Comment by claesrosell** [comment]
Yes. org.eclipse.birt.core re-exports with another set of access rules:

![bild](https://user-images.githubusercontent.com/8941815/191247310-98107159-3c2c-490a-95f1-44248f7cd773.png)

I agree, re-exporting is generally not a good idea.

**Comment by claesrosell** [comment]
org.eclipse.datatools.connectivity.oda is dependent on ULocale and exposes it via API, which we are consuming. Currently, it would not be possible to remove ICU4J.

**Comment by wimjongman** [comment]
I have fixed the ICU issue.

**Comment by wimjongman** [comment]
The latest builds are here https://github.com/eclipse/birt/actions/runs/3100143067
My changes are here: gh pr checkout 1052

**Comment by claesrosell** [comment]
> Ok, it took me two full days but the build is working again.
> 
> The reason for the failure was the update to the recent platform repository which required jetty 10.0.11 which required slf4j 2.0.0.sh6, etc..
> 
> The bad new is that the webviewer stopped working. @claesrosell could you take a look at this issue?

Sure thing, I will take a look at it. I cannot start immediately but perhaps later this week.

**Comment by claesrosell** [comment]
I just want to give you an update: I have the web viewer working on my machine now. It is a small fix, but I will not be able to push something today.

**Comment by claesrosell** [comment]
I am a bit new to this "check out PR" thing and contribute back to the PR. How do you want my changes? Can I push 
to "https://github.com/eclipse/birt.git" "refs/pull/1052/head" or should I push my local PR-1052 branch to my repo so you can cherry-pick it? I am a bit scared about the first option.

**Comment by wimjongman** [comment]
Thanks, Claes!

Sure, push to that same PR. I still have the changes locally. Otherwise push to your branch or even tell me what I have to change.

**Comment by claesrosell** [comment]
I failed to push directly to the PR. I pushed my changes to my repo instead. The branch is based on the PR, so you should be able to incorporate the changes into your branch pretty easily. Here is the commit.
https://github.com/claesrosell/birt/commit/f00804abfb6d652821c9a0873bd6da740edcb05a

I main thing is that the Jetty connector properties was switched back to jetty.http.port/host. I also removed the old maven "replace" things that made the jetty-selector.xml work for the "mars profile". + Removed declarations of precompiled JSP pages since they cause warnings when running from the IDE.

**Comment by wimjongman** [comment]
Cheers! Can you make a PR based on that commit? If you do, I can get that instead of adding you as a remote.

**Comment by claesrosell** [comment]
I made the PR directly against your branch:
https://github.com/wimjongman/birt/pull/1

**Comment by wimjongman** [comment]
Thanks, Claes! Everything works again.
