### ISSUE TITLE
Cannot create a new Driver Class needed for my Data Source

### ISSUE THREAD

**Issue by Roone** [eclipse/birt#1053]
I have the jar, and I "add" it using the Manage Drivers screen when trying to create my Data Source.

I can see the jar appears in the ~/drivers directory, but I would expect that a new Driver Class Name would appear in order that it then show in the dropdown menu so that I can properly create my Data Source. 

[AddNewDriver.docx](https://github.com/eclipse/birt/files/9629939/AddNewDriver.docx)

**Comment by hvbtup** [comment]
Please don't add proprietary file formats here.
You can add screenshots etc directly to your answers.

**Comment by Roone** [comment]
I cannot get the Driver Class dropdown to populate.

I can add the jar, or even manually place it in the plugins directory, and yet the Driver Class dropdown never changes and never shows me my driver.

**Comment by hvbtup** [comment]
I am using the Oracle JDBC driver by manually putting ojdbc7.jar into plugins\org.eclipse.birt.report.data.oda.jdbc_*.v*\drivers directory (the * are depending on the BIRT release).
This should work for any JDBC driver.
Maybe your driver  JAR file has additional dependencies (other Java classes or DLLs) and the JVM fails to find these?

**Comment by hvbtup** [comment]
Don't know, but probably you should look at https://www.oracle.com/database/technologies/faq-jdbc.html.
In fact, the ojdbc driver version you should use is depending on the JDK version and the RDBMS version.

Oracle JDBC can use the thin driver (pure Java) or a C-based driver (based on ODPI or classic OCI). The latter also needs DLLs.
But AFAIK you would notice missing DLLs for the OCI driver only when you actually try to connect.
