### ISSUE TITLE
Export word/pdf, how to add/generate table of contents (TOC)?

### ISSUE THREAD

**Issue by fadeli1** [eclipse/birt#1054]
need help

**Comment by hvbtup** [comment]
If you mean an automatically generated *visible* TOC: No!

You can create a visible TOC with clickable links yourself (using hyperlinks and bookmarks).
But you won't be able to render the corresponding page numbers in the TOC.

**Comment by fadeli1** [comment]
OK, thanks

**Comment by fadeli1** [comment]
@hvbtup 
Is it possible to customize the value of parameter "tocLevel "?

**Comment by hvbtup** [comment]
I don't think so.

If you mean the maximum level for the TOC: Just avoid creating TOC entries which you don't want.
TOC entries are created manually in the group editor dialog, but you can clear the field in the dialog.

The level at which a TOC entry is generated is computed automatically from the layout structure.

**Comment by fadeli1** [comment]
example:
```
1 xxx (This is a label, the value of toc is "1 xxx")
1.1 xxx (This is a label, the value of toc is "1.1 xxx")
1.1.1 xxx (This is a label, the value of toc is "1.1.1 xxx")
```
After exporting word
```
{ TC"1 xxx"\f C \l "1"}
1 xxx
{ TC"1.1 xxx"\f C \l "1"}
1.1 xxx
{ TC"1.1.1 xxx"\f C \l "1"}
1.1.1 xxx
```
I hope it is
```
{ TC"1 xxx"\f C \l "1"}
1 xxx
{ TC"1.1 xxx"\f C \l "2"}
1.1 xxx
{ TC"1.1.1 xxx"\f C \l "3"}
1.1.1 xxx
```
That's why I want to manually set the tocLevel value

**Comment by hvbtup** [comment]
You would have to use (kind of artificial) groups then.
But I don't know if the Word emitter uses these like the PDF emitter.

**Comment by fadeli1** [comment]
Change it like that?
```
1 xxx
1.1 xxx
1.1.1 xxx
```
to 
```
1 xxx (table > group -> label)
1.1 xxx (table > group -> label)
1.1.1 xxx (table > group -> label)
```

**Comment by hvbtup** [comment]
different groups of the same table item

**Comment by fadeli1** [comment]
I can't put it in the same table for fear of nesting too much content
```
1 xxx (table > group -> label)
...（There's more to it, like a table or a grid, etc）
1.1 xxx (table > group -> label)
...（There's more to it, like a table or a grid, etc）
1.1.1 xxx (table > group -> label)
...（There's more to it, like a table or a grid, etc）
```

**Comment by hvbtup** [comment]
Sorry, I don't understand why nesting should be a problem.
Our reports are often nested 4 or 5 levels of list/table items plus a handful of groups.

**Comment by fadeli1** [comment]
In nested tables, the lines on the left and right side of the table are often obscured, making it difficult to adjust for normal display.

**Comment by fadeli1** [comment]
example
![test](https://user-images.githubusercontent.com/1914030/192333398-8132d130-00ba-4e26-8575-8b673a83b797.png)

**Comment by hvbtup** [comment]
But this is only an annoyence in the layout editor and does not occur at runtime.
