### ISSUE TITLE
Fatal: I merged in the wrong direction!

### ISSUE THREAD

**Issue by hvbtup** [eclipse/birt#1058]
@wimjongman @claesrosell 

It seems I merged from triestram-partner/birt to eclipse/birt instead of the intended opposite direction.

Please - can someone revert this? I'm not sure I can do this... (seems my brain is in standby mode today)

**Comment by claesrosell** [comment]
@wimjongman, do you have an up-to-date master branch which you can force push? I have not, it is a bit out-dated.

**Comment by hvbtup** [comment]
It's a bit urgent because the merge also modified the README.md
I'm pretty sure there is a recommended and easy way to revert a merge, but I don't know *how* and as I already messed things up, I don't want to make it even worse.

**Comment by claesrosell** [comment]
If not I guess one could do a hard reset to the previous commit, which I think was : 6dbd23c93df6db02818bb490c9c6f1a767eee9c4

Like this:
git reset --hard 6dbd23c93df6db02818bb490c9c6f1a767eee9c4

And force push it. I am not very good at these things though. I am always terrified when I need to do them.

**Comment by hvbtup** [comment]
@claesrosell Me too!

A quick search for GutHub revert pull request found this:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request

Is that worth a try?

**Comment by hvbtup** [comment]
To answer my own question: Probably not. I don't find a corresponding PR on the PR page.

**Comment by claesrosell** [comment]
... but were you creating a pull request? Didn´t you just push?

**Comment by hvbtup** [comment]
I used the GH web site. So probably it was just push without a PR.

**Comment by hvbtup** [comment]
I checkout out master and performed the command

    git reset --hard 6dbd23c93df6db02818bb490c9c6f1a767eee9c4

The local files and the log are looking good then.
Not sure if I should dare pushing though

**Comment by cpfeiffer** [comment]
FWIW, you can also git revert the merge commit. You would have to do this on the current repo state, not on the state that you have already reset. But I cannot say if the owners would prefer to not have the commit in the history at all.
```
git revert c38c2bd14252245fe272385d63c8eb271455cdc3
git push
```

**Comment by claesrosell** [comment]
We do not want to have the commit in the history at all. 
@hvbtup If your state looks good I think that you should push. It would be good to have @wimjongman blessing though.

**Comment by hvbtup** [comment]
So after the reset, the command would be

    git push --force-with-lease

Tried to call Wim by phone, but couldn't reach him.

I think I should perform the push now. 
@ruspl-afed What do you think?

**Comment by claesrosell** [comment]
I have not used --force-with-lease , only --force.  But after a quick google search it seems like -with-lease is the preffered way.
Go ahead and push. I have fetched the current state into my fork and branced of prior to your last push. I think that we are safe.

**Comment by hvbtup** [comment]
Did so. Looks good to me.

Lessons learned:
- I'll book a Git training course with focus on GH.
- The GitHub UI is somewhat confusing. I'll have to be extra-careful when using it. Seems better to use the command-line.

**Comment by wimjongman** [comment]
Sorry I did not see this thread earlier. But it was fun to read :)

You did well. 

I wondered why the build had kicked in without changes in the master branch. Now it is clear :)
