### ISSUE TITLE
Setup of BIRT Dev Environment fails

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#1072]
### Discussed in https://github.com/eclipse/birt/discussions/1060

<div type='discussions-op-text'>

<sup>Originally posted by **hvbtup** September 26, 2022</sup>
I'm trying to build BIRT from source using Eclipse IDE 2022-09.

On a refresh, I get an error popup (BTW this also happened before #1058):
![grafik](https://user-images.githubusercontent.com/7644776/192278248-2c778829-8a7c-41d0-9dc9-6032ceba84de.png)

So I tried to install the Eclipse IDE anew,
but when I choose BIRT in the Eclipse Installer and continue until the Finish button, it fails with an error message:

Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:434)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:344)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3792)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1664195510779
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Tycho Project Configurators 0.9.0.201811261502 (org.sonatype.tycho.m2e 0.9.0.201811261502) requires 'osgi.bundle; org.eclipse.m2e.core [1.4.0,2.0.0)' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1664195510779
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.sonatype.tycho.m2e.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Tycho Project Configurators 0.9.0.201811261502 (org.sonatype.tycho.m2e.feature.feature.group 0.9.0.201811261502)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.sonatype.tycho.m2e [0.9.0.201811261502,0.9.0.201811261502]

Took 2 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

I don't know if these two different issues are related or not.
</div>

**Comment by wimjongman** [comment]
@hvbtup Ed made a fix. Can you try again?

**Comment by wimjongman** [comment]
@merks Ed, it unfortunately still fails. I get a popup to accept unsigned content, and then pressing accept or decline cancels the process:

![image](https://user-images.githubusercontent.com/180969/193111888-0c61f37c-5a40-42c3-bf36-32224f08f30e.png)

<details>
<summary>Output of Eclipse installer</summary>

```
Executing bootstrap tasks
Renamed existing configuration folder to C:\Apps\eclipse\oomph\birt-master3\eclipse\configuration.1664475247551
OpenJDK Runtime Environment 16.0.2+7-67
Product org.eclipse.products.epp.package.committers.latest
Workspace C:\Apps\eclipse\oomph\birt-master3\ws
Project org.eclipse.birt.master
Bundle org.eclipse.oomph.setup 1.21.0.v20210808-1248, build=5169, branch=4f2d83d895798b31dc987dc9c07da7c94b536f1d
Bundle org.eclipse.oomph.setup.core 1.21.0.v20210828-0732, build=5169, branch=4f2d83d895798b31dc987dc9c07da7c94b536f1d
Bundle org.eclipse.oomph.setup.installer 1.22.0.v20210817-0859, build=5169, branch=4f2d83d895798b31dc987dc9c07da7c94b536f1d
Bundle org.eclipse.oomph.setup.p2 1.17.0.v20210601-0619, build=5169, branch=4f2d83d895798b31dc987dc9c07da7c94b536f1d
Performing P2 Director (Eclipse IDE for Eclipse Committers (2022-12))
Offline = false
Mirrors = true
Resolving 33 requirements from 3 repositoriesto C:\Apps\eclipse\oomph\birt-master3\eclipse
Requirement org.eclipse.equinox.p2.iu:epp.package.committers [4.25.0,5.0.0) (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=win32)(osgi.ws=win32))))
Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group [4.25.0,5.0.0)
Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.feature.group [4.25.0,5.0.0)
Requirement org.eclipse.equinox.p2.iu:org.eclipse.buildship.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.e4.core.tools.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.eclemma.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.gitflow.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.epp.mpc.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.source.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.jgit.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.jgit.http.apache.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.lemminx.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.pde.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.pde.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.pde.source.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.source.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.source.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.swt.tools.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.tm.terminal.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.embedder.node.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.targlets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.pde.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.workingsets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.jdt.feature.group
Repository https://download.eclipse.org/technology/epp/packages/2022-12
Repository https://download.eclipse.org/releases/2022-12
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository https://download.eclipse.org/technology/epp/packages/2022-12
Adding repository https://download.eclipse.org/releases/2022-12
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Calculating requirements and dependencies.
Computing prerequisite plan
Collecting 4 artifacts from https://download.eclipse.org/releases/2022-12
Downloading epp.package.committers.executable.win32.win32.x86_64
Downloading org.eclipse.platform_root
Downloading org.eclipse.rcp_root
Downloading org.eclipse.platform.ide.executable.win32.win32.x86_64
Collected 4 artifacts for https://download.eclipse.org/releases/2022-12 in 0.618s
The engine operation was cancelled and the changes are being rolled back.
Took 27 seconds.
Task execution was canceled.
Press Back to choose different settings or Cancel to abort.
```
</details>

**Comment by merks** [comment]
This looks like a very old prompt dialog.   Is this using a very old installer?

**Comment by wimjongman** [comment]
I have no idea. I assumed the installer did an auto-update. This is what the weblink activates:

![image](https://user-images.githubusercontent.com/180969/193146784-1391eba5-faeb-4c1e-a443-433512bd439e.png)

**Comment by merks** [comment]
That's ancient.  Download a new one.

**Comment by hvbtup** [comment]
ATM when I start a freshly downloaded Eclipse installer, it fails with the following message:
![grafik](https://user-images.githubusercontent.com/7644776/193204493-4fdfd019-adc3-451b-ab45-20e4d8c7a74c.png)

**Comment by merks** [comment]
Are you inside a corporate firewall?   Those are often problematic. Sometimes even configuring the network proxy doesn't solve the problem because the firewall might inject certificates into the traffic flow that are not in the cacerts of the Java runtime used by the installer.  What kind of environment are you in?

**Comment by hvbtup** [comment]
No corporate firewall AFAIK.
This did not happen when I created the ticket #1060 this Monday.
And our admin is ill at home since two weeks I'm pretty sure we did not change anything on our side.
Does the Ecipse Installer work for others ATM?

**Comment by merks** [comment]
I think there is a real network problem at the Eclipse end of things!  

When I open this file:

https://www.eclipse.org/setups/setup.zip

It redirects to here:

https://projects.eclipse.org/projects/technology.set

That's probably why this build failed overnight:

https://ci.eclipse.org/oomph/job/marketplace-analyzer/432/

**Comment by merks** [comment]
I created this issue:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2019
