### ISSUE TITLE
org.eclipse.birt.runtime artifact corrupt/incomplete in maven

### ISSUE THREAD

**Issue by cmwarre** [eclipse/birt#1081]
I'm trying to use BIRT as a dependency for a project of mine, and I'm getting the following error when trying to include the latest build in Maven.  

`ZipException opening "org.eclipse.birt.runtime-4.10.0.jar": zip END header not found`

This is my dependency configuration.  Hopefully I'm grabbing it from the right place?  
```
        <dependency>
            <groupId>org.eclipse.birt</groupId>
            <artifactId>org.eclipse.birt.runtime</artifactId>
            <version>4.10.0</version>
        </dependency>
```

**Comment by hvbtup** [comment]
Not sure, but AFAIK #625 is still open (unsolved), so you won't find BIRT 4.10 on Maven.
You can download the articfacts from https://download.eclipse.org/birt/downloads/drops/R-R1-4.10.0-202210031241/

**Comment by cmwarre** [comment]
Interesting that I found an artifact online then.  

By chance do you know where a list of dependencies for the project are?  I'm not seeing them in the pom.xml files but is that because they're managed elsewhere?

**Comment by wimjongman** [comment]
Cody, BIRT consists of dozens of projects. For each project, you can find its dependencies in the MANIFEST.MF file.

**Comment by cmwarre** [comment]
> Cody, BIRT consists of dozens of projects. For each project, you can find its dependencies in the MANIFEST.MF file.

Is it just for historical reasons that this isn't done with maven?  I guess I'm mostly just seeing if that's on the "to do" list for getting the automatic maven publishing to maven central working or If I'm completely misunderstanding how dependency management works.
