### ISSUE TITLE
Outdated update site links in features

### ISSUE THREAD

**Issue by ajohnson1** [eclipse/birt#1108]
I noticed that the feature jar org.eclipse.birt.engine.runtime_4.10.0.v202210011458.jar had `feature.xml` with

```
   <url>
      <update label="%updateSiteName" url="http://download.eclipse.org/birt/update-site/4.9"/>
      <discovery label="%updateSiteName" url="http://download.eclipse.org/birt/update-site/4.9"/>
   </url>
```
so the wrong update site.

Running [Search for `update-site` on GitHub birt](https://github.com/eclipse/birt/search?p=1&q=update-site) shows quite a few other cases where the update site reference has not been changed for a new version of BIRT.

These should be updated for each release (not sure what to do while developing 4.11 as the 4.11 update site won't be live, but it probably doesn't matter as developers will know that and can fix it if needed.)

**Comment by wimjongman** [comment]
Thanks for noticing. These all need to be replaced with: https://download.eclipse.org/birt/update-site/latest/

Can you make a PR?

**Comment by gab1one** [comment]
Hi @wimjongman, I created a PR for this: https://github.com/eclipse/birt/pull/1163

**Comment by wimjongman** [comment]
Thanks, Gabriel!
