### ISSUE TITLE
Thick leader lines on pie chart after repeated Generator build/render drawImage

### ISSUE THREAD

**Issue by ajohnson1** [eclipse/birt#1121]
We use BIRT in [Eclipse Memory Analyzer](http://www.eclipse.org/mat)

I have noticed that resizing a window which has a BIRT drawn pie chart goes wrong on high resolution displays on Windows.

The code constructs a pie chart using a PieSeries.

It is then drawn using Generator.build() and then using a new GC and a new SWT Image, Generator.render() into the Image before a gc.drawImage to draw the chart into a SWT graphics context.

If the window is resized then the build/render/drawImage steps are repeated as the build bounds will have changed. Each time the steps are repeated the pie chart leader lines get thicker until they obscure the chart. Then after 20+ redraws the leader lines disappear. 

See [Bug 581154](https://bugs.eclipse.org/bugs/show_bug.cgi?id=581154) for images [Thick leader lines](https://bugs.eclipse.org/bugs/attachment.cgi?id=288866)

I think what is happening is the build step the [render code at Generator.java](https://github.com/eclipse/birt/blob/62d2ab909d7809c1a2942fb3d471f9427c38bd4d/chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/factory/Generator.java#L1018) does an `updateDeviceScale` which each time multiplies the leader line thickness in the chart. As the chart is not rebuilt each time the leader lines double in thickness until they eventually overflow to 0.

**Comment by wimjongman** [comment]
Hi, Andrew. I love MAT. Let's see if we can fix this. 

You state: "high resolution." Is this relevant?

I fixed the ChartExamples view so that they can run without Eclipse running,  but I do not see any resize artifacts. Please see attached. 

How do you trigger the render? Are you rebuilding the chart every time?


https://user-images.githubusercontent.com/180969/204896158-c6889260-add5-473f-85fa-a39bb2b7acab.mp4


https://user-images.githubusercontent.com/180969/204896184-9de92af3-2807-47da-b086-3ebbdf4cdf4c.mp4

**Comment by ajohnson1** [comment]
High resolution is relevant - it happens on my Windows 11 laptop at 2560x1600, 150% scale in display setting, but not at 125% scale or 150% scale. It doesn't occur at 1920x1200 with 125% scale.

The line `final int scale = idr.getDisplayServer().getDpiResolution() / 72;` must return at least 2 for the problem to occur, so getDpiResolution() >= 144.

The chart is only constructed once. On each resize, the code does a  Generator.build() and then using a new GC and a new SWT Image, Generator.render() into the Image before a SWT gc.drawImage to draw the chart into a SWT graphics context. 

The problem is that if scale >= 2 then the scale code in BIRT is executed every time gr.build() is done and it modifies the chart each time, doubling the line thickness.

I can fix the problem by instead of doing in my code:
`       state = gr.build(renderer.getDisplayServer(), chart, bo, null, rtc, null);`
doing:
`       state = gr.build(renderer.getDisplayServer(), chart.copyInstance(), bo, null, rtc, null);`

Is this the right way to solve the problem?

**Comment by wimjongman** [comment]
I found the bug. 

![image](https://user-images.githubusercontent.com/180969/209402035-88b19009-9b3c-4b7c-bc6e-bcb46365a495.png)

**Comment by wimjongman** [comment]
> I can fix the problem by doing: ` state = gr.build(renderer.getDisplayServer(), chart.copyInstance(), bo, null, rtc, null);`
> 
> Is this the right way to solve the problem?

The chart is the model of the renderer. The renderer updates the model,, so passing a copy will not reflect these changes in the original model. I'm not sure if this will have side effects.
