### ISSUE TITLE
Extreme high number of connections when using SQL Server Driver

### ISSUE THREAD

**Issue by roeltje25** [eclipse/birt#1139]
There is a very annoying issue when using complex reports with the SQL Server Driver. For every single query a new connection is created. We are using a Wildfly 26.1.2 instance where birt.war is running to service different RPTDESIGN files. We have configured a connection pool to the database which is used in the design files using odaJndiName property. This way we can manage the connections that are made on the server. After we migrated to the new app server, new drivers, etc. we found that the connection pool kept clogging up. This only happened when running BIRT reports.

After investigating the problem it seems that in  org.eclipse.birt.report.data.oda.jdbc.Connection in the method getMaxQueries() there is a conditional structure figuring out the max number of statements. In the instance of our SQL server the max statements is 0 (unlimited) and the max connections is 32767 (SQL Server max setting). The conditional then will return a max number of queries of 1 !!!! This makes every single query trigger a new connection. Instead I would expect that this method always returns 0 in case maxstatements =0., regardless of the number of maximum connections.

I have fixed the issue in  a fork here:
https://github.com/roeltje25/birt/blob/4.9.0-fixed/data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/Connection.java

that is for the specific version of birt we have isntalled. The issue is still there for the newer versions also.

**Comment by roeltje25** [comment]
Note that I adjusted the link above.

**Comment by wimjongman** [comment]
Hey Roel. Thanks for reporting. Please make a pull request so that we can get this in.

**Comment by roeltje25** [comment]
done: https://github.com/eclipse/birt/pull/1140
