### ISSUE TITLE
Splash screen not updated for 4.12

### ISSUE THREAD

**Issue by sumitpuri** [eclipse/birt#1145]
I tried to download and install BIRT 4.12 using these downloads- https://download.eclipse.org/birt/downloads/drops/latest/
However, after extraction, the version I see is 4.10 which is confusing.

Is 4.10 the latest version or 4.12?

<img width="450" alt="image" src="https://user-images.githubusercontent.com/6925028/208750905-919e30cb-27a4-4f65-92da-acafb7d29c73.png">

**Comment by wimjongman** [comment]
Ah, bummer. It is only the splash screen that we forgot to update. I will make a new splash without the version number because this will likely be forgotten in the future.

**Comment by wimjongman** [comment]
I accidentally pushed to master: https://github.com/eclipse/birt/commit/5a744c7287513d6b2d7d793953a291ae264d503f
