### ISSUE TITLE
No tags nor sources package for 4.12.0

### ISSUE THREAD

**Issue by peterdemaeyer** [eclipse/birt#1184]
The [landing page's](https://github.com/eclipse/birt/) `README.md` says **Latest version 4.10.0**, but [the link to the latest drop](https://download.eclipse.org/birt/downloads/drops/latest/) underneath points to a **4.12.0** binary. In the repository, I see no tag for 4.12.0 (nor 4.11.0), and the [latest sources one can download](https://github.com/eclipse/birt/releases) are 4.10.0. The fact that there is no tag makes it hard/impossible to download the sources for the 4.12.0 release.

My expectation is that for every release there is a corresponding tag and source release.

Can someone please tag the right commits appropriately and provide sources packages?

**Comment by wimjongman** [comment]
Thanks for reporting. This has been fixed.
