### ISSUE TITLE
RotatedText code does not dispose created TextLayout

### ISSUE THREAD

**Issue by hvbtup** [eclipse/birt#1200]
When the RotatedTextItem plugin is used in a report, an SWT warning about a "missing dispose" is shown in the error log(?) in the designer.

For a solution, see the change to the Java source file SwtGraphicsUtil.java in my cancelled PR #1084.

**Comment by priytosh-tripathi** [comment]
Hi @hvbtup ,

Can you please assign this task to me?

**Comment by priytosh-tripathi** [comment]
Hi @hvbtup ,

Please find the following PR for review:
https://github.com/eclipse/birt/pull/1203

**Comment by wimjongman** [comment]
Thanks for this, Priytosh!
