### ISSUE TITLE
Cryptography.PoorEntropy vulnerability issue

### ISSUE THREAD

**Issue by aianni** [eclipse/birt#1218]
Hi 
running a scan we found a Cryptography.PoorEntropy vulnerability issue
Stack trace:
java.util.Random.next(Random.java:205)
java.util.Random.nextInt(Random.java:329)
java.util.Random.nextBytes(Random.java:229)
org.eclipse.osgi.internal.container.InternalUtils.newUUID(InternalUtils.java:183)
org.eclipse.osgi.internal.framework.EquinoxConfiguration.initializeProperties(EquinoxConfigurati
on.java:1108)
org.eclipse.osgi.internal.framework.EquinoxConfiguration.<init>(EquinoxConfiguration.java:560)
org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:99)
org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:53)
org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:46)
org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:315)
org.eclipse.birt.core.framework.osgi.OSGILauncher.doStartup(OSGILauncher.java:163)
org.eclipse.birt.core.framework.osgi.OSGILauncher$1.run(OSGILauncher.java:77)
java.security.AccessController.doPrivileged(AccessController.java:747)
org.eclipse.birt.core.framework.osgi.OSGILauncher.startup(OSGILauncher.java:73)
org.eclipse.birt.core.framework.Platform.startup(Platform.java:73)

Please start using a more secure java.security.SecureRandom instead of java.util.Random

Regards
Andrea

**Comment by claesrosell** [comment]
The UUID generation of Equinox is not the Birt project's responsibility, but since it is configurable if SecureRandom or Random should be used, (by setting "equinox.uuid.secure" to "true") and the maintainers have set the use of "Random" as default, I think we can close this issue.
```
	public static String newUUID(EquinoxConfiguration config) {
		// Note that we use simple Random to improve
		// performance and the Framework UUID generation does not require
		// a full SecureRandom seed.
		boolean useSecureRandom = "true".equals(config.getConfiguration(EquinoxConfiguration.PROP_SECURE_UUID)); //$NON-NLS-1$
		byte[] uuidBytes = new byte[16];
		if (useSecureRandom) {
			new SecureRandom().nextBytes(uuidBytes);
		} else {
			new Random().nextBytes(uuidBytes);
		}
		...
```
