### ISSUE TITLE
Cryptography.InsecureAlgorithm vulnerability issue

### ISSUE THREAD

**Issue by aianni** [eclipse/birt#1219]
Running a scan we found a InsecureAlgorithm vulnerability issue

Stack: java.security.MessageDigest.getInstance(MessageDigest.java:195)
org.apache.xmlbeans.impl.values.JavaHexBinaryHolder.<clinit>(JavaHexBinaryHolder.java:133)
org.apache.xmlbeans.impl.schema.SchemaTypeImpl.createUnattachedNode(SchemaTypeImpl.jav
a:1934)
org.apache.xmlbeans.impl.schema.SchemaTypeImpl.createAttributeType(SchemaTypeImpl.java:1
089)
org.apache.xmlbeans.impl.values.XmlObjectBase.create_attribute_user(XmlObjectBase.java:960)
org.apache.xmlbeans.impl.store.Xobj.getUser(Xobj.java:1675)
org.apache.xmlbeans.impl.store.Xobj.add_attribute_user(Xobj.java:2272)
org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTColorImpl.setRgb(null:-1)
org.apache.poi.xssf.usermodel.XSSFColor.<init>(XSSFColor.java:120)
uk.co.spudsoft.birt.emitters.excel.StyleManagerXUtils.getXColour(StyleManagerXUtils.java:182)
uk.co.spudsoft.birt.emitters.excel.StyleManagerXUtils.addColourToFont(StyleManagerXUtils.java:
193)
uk.co.spudsoft.birt.emitters.excel.FontManager.createFont(FontManager.java:180)
uk.co.spudsoft.birt.emitters.excel.FontManager.getFont(FontManager.java:234)
uk.co.spudsoft.birt.emitters.excel.StyleManager.createStyle(StyleManager.java:155)
uk.co.spudsoft.birt.emitters.excel.StyleManager.getStyle(StyleManager.java:219)
uk.co.spudsoft.birt.emitters.excel.handlers.CellContentHandler.setCellStyle(CellContentHandler.j
ava:388)
uk.co.spudsoft.birt.emitters.excel.handlers.CellContentHandler.endCellContent(CellContentHandl
er.java:246)
uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableCellHandler.interruptCell(AbstractR
ealTableCellHandler.java:132)
uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableCellHandler.endCell(AbstractRealTa
bleCellHandler.java:81)
uk.co.spudsoft.birt.emitters.excel.ExcelEmitter.endCell(ExcelEmitter.java:345)
org.eclipse.birt.report.engine.emitter.CompositeContentEmitter.endCell(CompositeContentEmitte
r.java:126)
org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.endCell(HTMLTableLayoutEmi
tter.java:600)
org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.endCell(HTMLTableLayoutEmi
tter.java:600)
org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.endCell(HTMLTableLayoutEmi
tter.java:595)
org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.endContent(ContentEmitterUtil.java:110)
org.eclipse.birt.report.engine.layout.html.buffer.AbstractNode.end(AbstractNode.java:65)
org.eclipse.birt.report.engine.layout.html.buffer.HTMLPageBuffer.endCell(HTMLPageBuffer.java:2
18)
org.eclipse.birt.report.engine.layout.html.buffer.HTMLPageBuffer.endContainer(HTMLPageBuffer.
java:128)
org.eclipse.birt.report.engine.layout.html.buffer.TableBreakBuffer.endContainer(TableBreakBuffe
r.java:317)
org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.end(HTMLStackingLM.java:39)
org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:134)
org.eclipse.birt.report.engine.layout.html.HTMLInlineStackingLM.resumeLayout(HTMLInlineStack
ingLM.java:97)
org.eclipse.birt.report.engine.layout.html.HTMLInlineStackingLM.layoutNodes(HTMLInlineStackin
gLM.java:136)
org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.layoutChildren(HTMLStackingLM.jav
a:27)
org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:133)
org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStacki
ngLM.java:66)
org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.layoutChildren(HTMLStackingLM.jav
a:27)
org.eclipse.birt.report.engine.layout.html.HTMLRepeatHeaderLM.layoutChildren(HTMLRepeatHea
derLM.java:54)
org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:133)
org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStacki
ngLM.java:66

**Fix recommendation**
The preferred algorithms for symmetric key cryptography are AES and Twofish. For asymmetric key encryption, RSA is the standard
algorithm; for new development, use a minimum key length of 2048 bits. For hash algorithms, SHA-1 was the standard until recently.
However, SHA-1 now has some known theoretical weaknesses and is considered suspect.
Meanwhile, SHA-256 becomes the generally recommended hash function. NIST has mandated that as soon as practical, federal
agencies stop using SHA-1 and switch to the SHA-2 family of hash algorithms (such as SHA-224, SHA-256, SHA-384 and SHA-512) for
all but a few types of uses.
NIST encourages the use of SHA-2 algorithms for all new development.

**Comment by claesrosell** [comment]
org.apache.xmlbeans is not really the Birt project's responsibility. org.apache has its own bug tracker.

However,
the code which uses the "InsecureAlgorithm" (md5) is used for the calculation of hashes returned by Object.hashCode(). These hashes are always 32 bits (an int) and are mainly used by hashmaps in Java. Hash collisions by Object.hashCode() are totally ok.  If you want to know more about the hashCode() contract you can do so by reading the javadoc here: https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#hashCode()

My personal opinion is that this issue can be closed.

**Comment by hvbtup** [comment]
I agree with Claes. This is not a security issue, but a false positive.

**Comment by wimjongman** [comment]
Thanks, Claes. You sure know this stuff. Excellent.
