### ISSUE TITLE
Questions about table formatting

### ISSUE THREAD

**Issue by fadeli1** [eclipse/birt#1249]
I drew a table, the cell is a dynamic text, the contentType is html.

When there are multiple columns, there is no vertical center alignment.

![image](https://user-images.githubusercontent.com/1914030/227911627-bb1eece0-a5bb-4116-961e-538b181a54bd.png)

the contentType is other，center vertically.

sometimes I need to display superscript or subscript, so I have to use html type, like this <SUB>2</SUB>

**Comment by hvbtup** [comment]
?
The items in your image *are* centered vertically.
If you want to display the text centered across two cells, then you have to merge the cells.

**Comment by hvbtup** [comment]
Probably inside your table cell you have two items. The upper one is empty, but it is stil there (did you notice the little line-feed indicator?). You have to hide it if it is empty using the visibility expression.

**Comment by fadeli1** [comment]
here is my structure:
![image](https://user-images.githubusercontent.com/1914030/227988158-78bda7cf-4b17-4a85-91c0-f07ef5c7e7e3.png)

**Comment by hvbtup** [comment]
Then probably the empty paragraph is inside your html.

**Comment by fadeli1** [comment]
html is this?
![image](https://user-images.githubusercontent.com/1914030/227994172-6921c78a-9bf0-4a82-82f2-902ac6755812.png)
