### ISSUE TITLE
X-axis is not fully displayed

### ISSUE THREAD

**Issue by sanshigongA** [eclipse/birt#1285]
![image](https://github.com/eclipse/birt/assets/107231757/e1860b64-d801-4f78-bd90-37640d99a482)
![image](https://github.com/eclipse/birt/assets/107231757/6a79dd09-fe32-4c4f-a367-83ee84819c58)
As shown in the above image, the backend data is up to 2023-03-30, and the data displayed in the chart is also up to 2023-03-30. The x-axis in BIRT is automatically scaled, but the maximum value on the x-axis is 2023-03-29. How can I display the maximum value (2023-03-30) at the end of the x-axis?

**Comment by hvbtup** [comment]
I cannot answer your question, but displaying all the values in the chart doesn't make sense.
It is impossible for someone looking at the chart to see to which point in time a value is connected.

**Comment by sanshigongA** [comment]
> I cannot answer your question, but displaying all the values in the chart doesn't make sense. It is impossible for someone looking at the chart to see to which point in time a value is connected.

But it is not enough to give people a clearer understanding of the timeline of the data.

**Comment by wimjongman** [comment]
You have to reorganize your data in such a way that it fits. What you want is a table in a chart. This is only possible if you provide enough space. If you want to display all values then use a table. Use the chart for showing trends.
