### ISSUE TITLE
Provide contributors with an Oomph Setup to simplify setup of a BIRT IDE

### ISSUE THREAD

**Issue by Flugtiger** [eclipse/birt#596]
I have an Oomph setup file laying around in my fork and would love to integrate it into the real deal (and maybe even get it into the official Oomph catalogue). 😁 I just have to find the time to create the necessary pull requests...

**Comment by UrsZeidler** [comment]
We at @SerNet would appreciate this.

**Comment by ruspl-afed** [comment]
Ed @merks is it possible to add maven dependency to `setup.targlets:TargletTask` ? I  can found how to reference the .target file to be activated but nothing about Maven artifacts.

We have a number of dependencies in the form:
```xml
		<location includeDependencyScope="compile" includeSource="true" missingManifest="generate" type="Maven">
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>10.0.6</version>
			<type>jar</type>
		</location>
```
How would you handle this with Oomph?

**Comment by merks** [comment]
Sorry, there is no support for that.   Ideally someone would simply generate a Jetty update site that everyone can reuse, but that appears to be wishful thinking with both the Platform and WTP spinning such things, but only for the parts they respectively need.

**Comment by merks** [comment]
I did a bit of digging and found these:

https://github.com/eclipse/jetty.project/issues/6403
https://github.com/eclipse/jetty.project/pull/6404

So I found that these p2 update sites exist:

https://search.maven.org/artifact/org.eclipse.jetty/jetty-p2

These can be used directly by p2 using a URL like this:

jar:https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-p2/10.0.7/jetty-p2-10.0.7-p2site.zip!/

But resolution fails because
```
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1635751513019
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: org.eclipse.birt.rcp.feature.group 4.9.0.v20211101-082503 requires 'org.eclipse.equinox.p2.iu; org.eclipse.jetty.continuation 0.0.0' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1635751513019
```

If I remove that dependency, it gets further, but fails like this:
```
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=D__Users_test_birt-master_ws-1f7da47122711d3168e64bbe8212f2ea91b32f67, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.deploy,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.http,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.io,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.jndi,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.osgi.boot,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.plus,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.security,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.server,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.servlet,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.util,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.webapp,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
  ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Problems downloading artifact: osgi.bundle,org.eclipse.jetty.xml,10.0.7.
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 Signature is invalid for current content.
```
So that doesn't look so good... 

The above is an error from the new PGP signature verification that is produced here:

https://git.eclipse.org/c/equinox/rt.equinox.p2.git/tree/bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/processors/pgp/PGPSignatureVerifier.java#n222

A bug?

Perhaps a location in a *.target file doesn't do any verification?

**Comment by merks** [comment]
Investigating locally in an Oomph runtime instance I get a failure like this:
```
    ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=D__Users_merks_oomph-1.23_ws-IDE-0f0cce59e727abd0ac508a95d9159270dc7fb384, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
    ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to read repository at mvn:org.eclipse.jetty:jetty-util:10.0.7:jar:.
```
So clearly I'm missing the thing that registers the mvn protocol...

**Comment by ruspl-afed** [comment]
Ed @merks please also have a look at my PR #677 
I tried to use `pde:TargetPlatformTask` (that could postpone our battle with Jetty) but the .target is not activated for some reason (https://github.com/eclipse/birt/pull/677/files#r740025382 ). 
I'm using target file name without `.target` extension.

**Comment by wimjongman** [comment]
Guys, jetty is in the target platform. That needs to be activated.

**Comment by ruspl-afed** [comment]
The latest PR state contains activation of  https://github.com/eclipse/birt/blob/master/build/org.eclipse.birt.target/org.eclipse.birt.target.target

**Comment by wimjongman** [comment]
This one was fixed. Thanks all for pushing this. An important step forward.

Please use the new installer link and follow the instructions. The link is also available from the README.MD:

https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse/birt/master/build/org.eclipse.birt.releng/BIRTConfiguration.setup&show=true
