### ISSUE TITLE
Test results are not preserved by GitHub Actions

### ISSUE THREAD

**Issue by Flugtiger** [eclipse/birt#598]
To be able to analyse the results of a test run in GitHub Actions, the test results should be preserved after the build has ended.

**Comment by Flugtiger** [comment]
I just saw that the build logs are still accessible after the build. So maybe this issue is not that important after all.

**Comment by ruspl-afed** [comment]
> I just saw that the build logs are still accessible after the build. So maybe this issue is not that important after all.

Yes, what we have could be sufficient.
