### ISSUE TITLE
CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by Flugtiger** [eclipse/birt#599]
The file CONTRIBUTING.md seems to contain the Eclipse.org login page html.

@waynebeaton you added this file, what was your intention?

**Comment by waynebeaton** [comment]
Brain fart. I noticed it immediately and pushed another commit. The CONTRIBUTING.md in HEAD is, AFAICT, correct.

**Comment by Flugtiger** [comment]
Sorry, I must have been on a PRs branch or something...
