### ISSUE TITLE
Pull request builds 2 times

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#612]
See below. why does it build twice?

![image](https://user-images.githubusercontent.com/180969/110995141-241c1100-837a-11eb-95c8-386aba026f95.png)

**Comment by Flugtiger** [comment]
I guess it builds the first time, because it's a push to a branch in this repo and the second time, because there is a pull request on this branch. To make a pull request one should use a branch in ones fork and not in the official repo.

**Comment by wimjongman** [comment]
Can you fix it so that it only builds when there is a push to master?

**Comment by wimjongman** [comment]
Fixed!
