### ISSUE TITLE
How to handle the Jetty inclusion

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#621]
Jetty is no longer in the release train. This has the following drawbacks:

1. When we build against a given target (e.g. 4.11), we also consume jetty from that target
2. When we install BIRT into a newer target (e.g. 4.19) old jetty bits may get included.

This was causing the viewer to break when installing 4.9 (from Mar 17 2021) into 4.19. 

The BIRT feature **_included_** the `o.e.jetty.osgi.boot` bundle which clashed with newer jetty versions. This inclusion was removed with commit 161d153

To install the viewer correctly the jetty 9.x update site must be added to the available update sites.

We need to find a fix for it.

**Comment by hvonbargen** [comment]
The previewer not working is a real show-stopper.

**Comment by wimjongman** [comment]
I am working on including jetty. The effort is combined with #640

**Comment by hvbtup** [comment]
To avoid confusion: The issue I am seeing is that when unzipping the generated birt-report-designer-all-in-one-4.9.0-2021*-win32.win32.x86_64.zip, calling eclipse.exe there, switching to the Report Design perspective, open any report and  and then selecting the menu entry Run -> View Report -> As PDF (or As HTML) this results in

    HTTP ERROR 503
    Problem accessing /viewer/preview. Reason:
    Service Unavailable
    Powered by Jetty:// 9.4.15.v20190215

So it seems like Jetty is included somehow, but obviously BIRT and Jetty don't like each other. Is this the issue you describe here?

**Comment by wimjongman** [comment]
Yes.

**Comment by hvbargen** [comment]
Did you read https://www.optimaw.ch/change-to-jdk11-lts/ ?
It seems as if this is a little complicated, but solvable. At least Andrej Dimic  seems to have solved it.

**Comment by wimjongman** [comment]
I wish I had seen this sooner. I basically went through the same research. Please note that the current HEAD is now compiling with JDK11.

**Comment by adiinfo-77** [comment]
you can get the compiled jetty-plugin here; https://www.optimaw.ch/nexus/#browse/browse:birt-reloaded, if needed.

**Comment by wimjongman** [comment]
Fixed and verified.
