### ISSUE TITLE
Maven build doesn't work for me

### ISSUE THREAD

**Issue by hvbargen** [eclipse/birt#626]
Sorry, doing this in my holiday, so I cannot communicate over birt-dev. I'm trying to create some PRs to fix some bugs as I announced in birt-dev.

Wim said that the Travis build is working. But after cloning a fresh fork of the GubtHub repo,

    mvn package -DskipTests

does not work for me (I'm using JDK8).

It results in
[INFO] Resolving dependencies of MavenProject: org.eclise.birt:birt-report-all-in-one:4.9.0-SNAPSHOT @ D:\git-repos\birt\birt\build\birt-packages\birt-report-all-in-one\pom.xml
[INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.birt.report.designer.all 4.9.0.qualifier
[ERROR]   Missing requirement: org.eclipse.birt.report.designer.all 4.9.0.qualifier requires 'org.eclipse.mylyn.bugzilla_feature.feature.group 0.0.0' but it could not be found

 Am I missing an important point? 

These build problems were the main reason why I forked hvbtup/birt from flugtiger/birt instead of directly from eclipse/birt.

**Comment by wimjongman** [comment]
try `mv clean verify -DskipTests`

**Comment by ruspl-afed** [comment]
@wimjongman tests are failing after the latest merge to master

**Comment by hvbargen** [comment]
mvn clean verify -DskipTests had the same result. I also deleted my .p2 and .m2 directories before I tried to build (as was recommended somewhere), but that didn't help.

**Comment by wimjongman** [comment]
The Jenkins build is green. it builds like this:

jdk8
maven-latest
clean verify --no-transfer-progress -U -DskipTests

**Comment by wimjongman** [comment]
> 
> 
> @wimjongman tests are failing after the latest merge to master

Ah, should we revert d9439c728eb469d6c25d6f83ec1ab1eed6426405?

**Comment by hvbargen** [comment]
That commit cannot be related to this problem.
Is the mvn command working on your machines (after you rename the .m2 and .p2 directories to have a clean environment)?

**Comment by hvbargen** [comment]
Wait ... 
Maybe my fault: I had a Java 11 JDK in the PATH environment variable. Corrected this (so that JDK 8 is used in JAVA_HOME and in PATH environment variables) and the build is running (well, it takes >30min on my machine).
I'll update the ticket when the build is done.

**Comment by hvbargen** [comment]
This is a bit embarassing.
Now that my environment is clean (no JDK 11 on the PATH anymore), the build was successful (it took 33 min). I am using JDK 8, Maven 3.6.3 on Windows 10, and the command

    mvn clean verify --no-transfer-progress -U -DskipTests

Thanks for your help anyway!
The failing test which Alexander reported is a different issue, so I'll close this one.

**Comment by hvbargen** [comment]
BTW My bug fixes will have to wait until tomorrow...

**Comment by wimjongman** [comment]
Thanks for the verification.

**Comment by ruspl-afed** [comment]
> Ah, should we revert d9439c7

That would be logical. Do you think we can ask the contributor of this change to fix the test?

**Comment by wimjongman** [comment]
Yes, we can ask that. Please go ahead.
