### ISSUE TITLE
All-In-One for MacOSX

### ISSUE THREAD

**Issue by annblackz** [eclipse/birt#653]
Hello,

I am running on macosx Catalina.  I cloned the latest repo and successfully built.  However, it appears as if the all-in-one only built for win32?  Is there something I can do such that it will build for mac osx?

Thanks so much,

Ann BZ

**Comment by annblackz** [comment]
I was able to make changes to some build files to build for macosx and get a successful build.  I am currently testing and will post some simple instructions on what I changed after I poke around it more.  Thanks.

**Comment by annblackz** [comment]
Here are the changes I made.  The Report Viewer as PDF from within Eclipse did not work.  Otherwise, I could view and edit report templates.

diff --git a/build/birt-packages/birt-runtime-osgi/build.xml b/build/birt-packages/birt-runtime-osgi/build.xml
index f732f0aa16..19b9f197bb 100644
--- a/build/birt-packages/birt-runtime-osgi/build.xml
+++ b/build/birt-packages/birt-runtime-osgi/build.xml
@@ -6,7 +6,8 @@
   <property name="ENGINE_DIR" location="${STAGE_DIR}/ReportEngine/"/>
   <property name="VIEWER_DIR" location="${STAGE_DIR}/WebViewerExample"/>
   <property name="PRODUCT_DIR" location="./target/products/org.eclipse.birt.engine.runtime/win32/win32/x86_64/ReportEngine"/>
-  <property name="DESIGNER_DIR" location="${ROOT_DIR}/build/org.eclipse.birt.p2updatesite/target/products/org.eclipse.birt.designer/win32/win32/x86_64/designer"/>
+  ^M
+  <property name="DESIGNER_DIR" location="${ROOT_DIR}/build/org.eclipse.birt.p2updatesite/target/products/org.eclipse.birt.designer/macosx/cocoa/x86_64/designer.app/Contents/Eclipse"/>^M
   <target name="package" depends="build-report-engine, build-webviewer, build-webviewer-war">
     <zip destfile="./target/birt-runtime-osgi-${BIRT_VERSION}.zip">
       <fileset dir="${STAGE_DIR}"/>
diff --git a/build/org.eclipse.birt.api/build.xml b/build/org.eclipse.birt.api/build.xml
index 44dcb06609..e23db06fe9 100644
--- a/build/org.eclipse.birt.api/build.xml
+++ b/build/org.eclipse.birt.api/build.xml
@@ -6,7 +6,7 @@
        <property name="LIB_DIR" location="./target/lib" />
        <property name="ROOT_DIR" location="../../" />
        <property name="P2UPDATESITE_DIR" location="../org.eclipse.birt.p2updatesite/" />
-       <property name="PRODUCT_DIR" location="${P2UPDATESITE_DIR}/target/products/org.eclipse.birt.designer/win32/win32/x86_64/designer/" />
+       <property name="PRODUCT_DIR" location="${P2UPDATESITE_DIR}/target/products/org.eclipse.birt.designer/macosx/cocoa/x86_64/designer.app/Contents/Eclipse" />
        <target name="clean">
                <delete dir="./target" />
        </target>
diff --git a/docs/org.eclipse.birt.doc.isv/BuildISVDoc.xml b/docs/org.eclipse.birt.doc.isv/BuildISVDoc.xml
index f1fc5163c7..fac1302e8c 100644
--- a/docs/org.eclipse.birt.doc.isv/BuildISVDoc.xml
+++ b/docs/org.eclipse.birt.doc.isv/BuildISVDoc.xml
@@ -194,6 +194,7 @@
                 <antcall target = "coreuiJavadoc"/>
                 -->
                
+                
        </target>
 
        <target name="cleanBuild" description= "clean files generated by build">
diff --git a/pom.xml b/pom.xml
index b617fe7612..034fc318ac 100644
--- a/pom.xml
+++ b/pom.xml
@@ -331,8 +331,8 @@
                                        <includePackedArtifacts>false</includePackedArtifacts>
                                        <environments>
                                                <environment>
-                                                       <os>win32</os>
-                                                       <ws>win32</ws>
+                                                       <os>macosx</os>
+                                                       <ws>cocoa</ws>

**Comment by wimjongman** [comment]
See the build instruction in README.MD in the root.
