### ISSUE TITLE
SVG support for pptx format

### ISSUE THREAD

**Issue by Krzysiek-SS** [eclipse/birt#663]
Hi,

Does Birt support export chart in SVG format into PowerPoint slides? If no is there is any idea or plan how/when that feature be added ? 

Thanks For Help

**Comment by wimjongman** [comment]
Why would you want to have SVG format in PP slides? There is no plan to provide this, but you can contribute it if you can.

**Comment by Krzysiek-SS** [comment]
Thanks for answer. Our solutions allow to provide pdf or pptx reports to end user. Potentially we imagine that pdf is non editable report and pptx can be editable, like move legend, adjust colors. 
Regard contribution, we need to make decision if we reject that functionality or any we will provide that. I reviewed MS shapes and at first look it does not look quite forward to convert svg to theirs format. It is actually MS fault istead of provide full support for svg they decided to implement conversion during import/export.

**Comment by hvbtup** [comment]
@wimjongman I think this should be closed. MS Office does not support SVG, so BIRT cannot support SVG in MS Office format output, be it Word or Excel or PowerPoint.

**Comment by wimjongman** [comment]
Thanks, @hvbtup
