### ISSUE TITLE
Create Eclipse Installer setup for BIRT

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#670]
Ed @merks, when you have time, can you whip up a setup for us as you did for WB?

The project set file is at the root of the repo
Our website is here: https://github.com/eclipse/birt-website

I am currently moving BIRT to 2021 via the issue:   How to import BIRT code into eclipse #628

**Comment by ruspl-afed** [comment]
I plan to:
1. branch from master, 
2. add the work from Ed @merks 
3. add my work above this 
4. improve until usable

**Comment by ruspl-afed** [comment]
@wimjongman I think this one duplicates #596

**Comment by wimjongman** [comment]
Yes!
