### ISSUE TITLE
Review ReportLauncherUtils.java:

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#671]
This class could not be compiled against latest eclipse. Review what needs to be done here.

UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/internal/ui/launcher/util/ReportLauncherUtils.java:

**Comment by claesrosell** [comment]
This class has a lot of discouraged things going,
I did some digging in old Eclipse code and found out that the old ICoreConstant.PLATFORM_PATH is replaced by a static method on TargetPlatform.  Just to get it to compile and work on the same level as recently the only thing that seems to be needed is to replace:

```
public static IPath getEclipseHome() {
	Preferences preferences = PDECore.getDefault().getPluginPreferences();
	return new Path(preferences.getString(ICoreConstants.PLATFORM_PATH));
}
```

with

```
public static IPath getEclipseHome() {
	return new Path(TargetPlatform.getLocation());
}
```

However, to use the location of the TargetPlatform to locate the EclipseHome might have been correct a decade ago, but probably not anymore.

Should we review the complete class or just get it to work?

**Comment by ruspl-afed** [comment]
It seems that this is not the only class that needs review. So I would focus on just getting it to work. The rationale behind this is to create our first release as soon as we can and then we can improve it gradually.
