### ISSUE TITLE
Do not embed fop but add it as a dependency

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#674]
Apache fop is embedded but it should be included.

**Comment by wimjongman** [comment]
IP REVIEW: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23815#c3

**Comment by ruspl-afed** [comment]
@wimjongman Wim, I pinged them but still no movement there. Should we ask @waynebeaton to intensify this a bit?

**Comment by waynebeaton** [comment]
> Should we ask @waynebeaton to intensify this a bit?

I guess that this question answers itself. :-)

I'll see what I can do.

**Comment by ruspl-afed** [comment]
@wimjongman please have a look at IP Team reply https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23815#c9

TBH I don't know the origin of the JAR that we currently have in our repository. But anyaway, are you OK if we remove some files from there?

**Comment by wimjongman** [comment]
the review has been completed.
