### ISSUE TITLE
Move license to EPL 2

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#683]
The current license is EPL1 and we must move to EPL2.

We need to replace the following files:

license.html
epl-v10.html

and fix all texts in feature.xml and feature.properties.

See examples of the new files here:

https://github.com/eclipse/nebula/tree/master/widgets/oscilloscope/org.eclipse.nebula.widgets.oscilloscope.feature

**Comment by SteveSchafer-Innovent** [comment]
I'll do this.  It's about my speed.

**Comment by SteveSchafer-Innovent** [comment]
What about all the copyright comments in the java files?

**Comment by ruspl-afed** [comment]
1) java files header should be modified to comply with EML2.0
2) about.html should be replaced with its EPL2.0 version
3) other textual files should obtain a license header if not yet

@SteveSchafer-Innovent please select one small bundle to apply EPL2.0 and we will discuss the required changes in details.

**Comment by wimjongman** [comment]
Alexander, is point 3 really needed or should we file a new issue and solve that post 4.9?

**Comment by ruspl-afed** [comment]
Wim, it should not be a big deal while it removes a lot of questions. Typically this is +several files per bundle, nothing notable comparing with amount of .java files.

**Comment by wimjongman** [comment]
Ok. Let's see. 

The java files can be changed using a smart regex find/replace. Same for the about.html.

**Comment by SteveSchafer-Innovent** [comment]
My plan is to change all the files with scripting of one form or another.

**Comment by wimjongman** [comment]
Maybe you can ask on cross project mailing list if someone already made these tooling. @vogella do you know.if there is eplv1-eplv2 tooling?

**Comment by SteveSchafer-Innovent** [comment]
How do I access the cross project mailing list?

**Comment by ruspl-afed** [comment]
https://www.eclipse.org/lists/cross-project-issues-dev/2021/Dec/index.html

**Comment by vogella** [comment]
I used regex expression for the main work and manual fixes then needed,  see here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=535802

**Comment by wimjongman** [comment]
> How do I access the cross project mailing list?

There is this thing called google ;)

**Comment by SteveSchafer-Innovent** [comment]
I've created awk scripts for license.html, about.html, feature.properties, epl-2.0.html files, and java files.  Should I delete the epl-v10.html files?  Still searching for more instances of the license but I should be ready to submit a PR soon.

**Comment by ruspl-afed** [comment]
Please, please, would you be so kind to not submit all the changes in one PR.

**Comment by SteveSchafer-Innovent** [comment]
I know, the changes are huge.  EVERY java file is changed.  Would you suggest one PR for each of the file types?

**Comment by ruspl-afed** [comment]
I would prefer to have 1 PR per bundle

**Comment by SteveSchafer-Innovent** [comment]
If bundles are instances of plugin.xml then there are 234 of them.  Is that what you mean?

**Comment by ruspl-afed** [comment]
Can we start from 1 (one) PR for the first bundle in the list?
This way we can agree on what should be done for every bundle having relatively small sample.

**Comment by SteveSchafer-Innovent** [comment]
That location doesn't contain epl-v10.html, feature.properties, or license.html, but it's a good test for about.html and java files.

For the copyright notice in java files, I made the script smart enough to pull the creation year from the existing notice but otherwise I ignored everything else and replaced it with this:

/*******************************************************************************
 * Copyright (c) <creation year>, 2021 Contributors to Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     See git history
 *******************************************************************************/

I could make the script pull the original contributor name if you think that's necessary.  Otherwise is this acceptable?

**Comment by ruspl-afed** [comment]
> That location doesn't contain epl-v10.html, feature.properties, or license.html

because this is not the feature location but bundle location. let's discuss features separately.

Regarding suggested header, @waynebeaton we need your advice

**Comment by waynebeaton** [comment]
That header is fine as a go-forward solution, but do not remove existing copyright statements.

For completeness, you can do things like add additional copyright holders or "and others" to an existing copyright statement. Or, you can add an entirely new copyright line to an existing header.

FWIW, I was pretty quickly able to identify a [header](https://github.com/eclipse/birt/blob/25fba3dd076dcc4e17a148218f65be4b6858d3b0/engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/bugfix/FixedRenderTask.java) that contains copyright information that is not reflected in the commit log (i.e., the copyright owner was not actually the author or committer of a commit).

**Comment by SteveSchafer-Innovent** [comment]
If I do not remove existing copyright statements, then I leave the reference to EPL-1, correct?

**Comment by waynebeaton** [comment]
No. You can/should change the license statement. Just leave the copyright statements intact.

**Comment by SteveSchafer-Innovent** [comment]
PR for https://github.com/eclipse/birt/tree/master/UI/org.eclipse.birt.report.debug.core submitted.  This project is fairly limited.  I've found license references in more files in other projects, including *.html, *.exsd, *.msg, various .properties and .xml files,   *.jj files, whatever those are.  Some of the html files will be a bit more challenging to parse.  I'll be committing the scripts to https://github.com/SteveSchafer-Innovent/Birt-Eclipse-License-Upgrade-Scripts.

**Comment by SteveSchafer-Innovent** [comment]
There are a number of license.properties files as well as *.msg files that contain a big text block that includes a reference to EPL 1.  Is it sufficient to change the reference to EPL 2 or do other parts of that text need to be changed?  Specifically there is a date near the top:

```
license=\
ECLIPSE FOUNDATION SOFTWARE USER AGREEMENT\n\
January 28, 2004\n\
```

**Comment by wimjongman** [comment]
Yes, that needs to be changed to correctly reflect the EPL2 header.

**Comment by wimjongman** [comment]
Yes, go ahead.

**Comment by wimjongman** [comment]
Thanks, Steve! A hell of a job. Well done.
