### ISSUE TITLE
BIRT Eclipse Installer gives error message 

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#690]
When I click the link on the front page and run the installer, I get an error message. Are there some magic sprinkles to be applied by @merks or @ruspl-afed ?

![image](https://user-images.githubusercontent.com/180969/140383067-54b5de8d-6198-4264-b9d7-df392ca2ea80.png)

**Comment by merks** [comment]
What do the details say?  How do I reproduce this problem?  Is it ready to add to the catalog?  What's the link?  So many questions...

**Comment by ruspl-afed** [comment]
We already discussed this. I need to create `BIRTConfiguration.setup` to tune the product selection

**Comment by wimjongman** [comment]
> 
> What do the details say? How do I reproduce this problem? Is it ready to add to the catalog? What's the link? So many questions...

I just click the link in the README.MD like I do for WB.

> 
> 
> We already discussed this. I need to create `BIRTConfiguration.setup` to tune the product selection

Sorry, I did not make the link. 

There is also an issue resolving the target platform from the setup. It does not resolve and is not set. When I open the target manually I can resolve and set.

**Comment by merks** [comment]
I'm happy to help.  Just let me know what you need/want...

**Comment by ruspl-afed** [comment]
> There is also an issue resolving the target platform from the setup.

This is interesting. It was working before the latest target change(s). Do you have a resolution error to post here?

**Comment by ruspl-afed** [comment]
Here is the resolution error

```
Committing the provisioning operation.
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:291)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.setup.pde.impl.TargetPlatformTaskImpl.perform(TargetPlatformTaskImpl.java:293)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3851)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3794)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5178)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2338)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5172)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:5170)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3785)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3760)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3638)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:600)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:727)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.m2e.core code=-1 Could not resolve artifact org.apache.jasper:glassfish:jar:2.2.2-v201205150955
    ERROR: org.eclipse.m2e.core code=-1 Missing org.apache.jasper:glassfish:jar:2.2.2-v201205150955
```

**Comment by wimjongman** [comment]
That commit 0d98911 fixed the target platform issue.

**Comment by merks** [comment]
I've added BIRT's project setup to the catalog:

https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/commit/?id=d85a783b20f1fbc4a85a4ee27346ffc826e50a27

I've made a few small changes to the BIRT.setup and added a BIRTConfiguration.setup.  Just unzip these to overwrite the file and add the new file.

[BIRT.zip](https://github.com/eclipse/birt/files/7481063/BIRT.zip)

Once these are committed I can test that the configuration works properly.  (Again, sorry that I don't know how to do the pull request thing yet.)

The error you get above is because you are dropping a Project setup on the installer, not a Configuration.  The link URL should be the URL for the BIRTConfiguration.setup.  Once you commit that file, the description will appear on the web page for the link because this job copies it to a location where it is accessible:

https://ci.eclipse.org/oomph/job/setup-archiver/

**Comment by merks** [comment]
There was some garbage XML in the project setup causing failures:

https://ci.eclipse.org/oomph/job/setup-archiver/

I've removed it from this version:

[BIRT.zip](https://github.com/eclipse/birt/files/7481183/BIRT.zip)

Please commit that so that the archiver stops failing.

**Comment by wimjongman** [comment]
Thanks, Ed! Alexander, are you on this?

>  (Again, sorry that I don't know how to do the pull request thing yet.)

Ed, it is very simple. 
* Fork the repository and start pushing to it. 
* Github will see the change and ask to create a PR for this main repo. 
 
It is much more efficient ;)

**Comment by merks** [comment]
Keep in mind that I have only ever used Gerrit where I did not need to fork something and push to it that.  So I don't know how to do this (with EGit).  Likely it should be self-evident, but it's new to me...

**Comment by ruspl-afed** [comment]
@merks I've created PR #691 based on your work.
Would you like to review it?

**Comment by wimjongman** [comment]
Keep in mind that for **non-committers** to be able to push changes, they need to push to their own fork. 

In the birth oomph setup we are referring to the master repository while in fact, we should be referring to the forked repository.

**Comment by merks** [comment]
I suppose that in the IDE one could somehow create a new local branch that references the remote fork/branch and push to that.  I wonder if you can create that new fork/branch in the IDE directly or if you need to do this in Github first and then hook up to that.  I will try to learn more for my next adventures in contributing to BIRT...

**Comment by ruspl-afed** [comment]
@wimjongman does it work for you after the merge of #691 ?

**Comment by wimjongman** [comment]
On the first screen, should HTTPS not be the preselected choice?

![image](https://user-images.githubusercontent.com/180969/140519513-72b1f335-9661-47df-b80a-5157149d91f2.png)

**Comment by wimjongman** [comment]
When leaving the git@github choice, it ends in error in the setup.


![image](https://user-images.githubusercontent.com/180969/140519834-9b95be97-58f7-4301-b8d2-2976b405e88a.png)

**Comment by ruspl-afed** [comment]
what is the header of the error?

**Comment by wimjongman** [comment]
> 
> what is the header of the error?

![image](https://user-images.githubusercontent.com/180969/140522195-e4f08836-e56c-49f5-bb8b-1adfa0878d3f.png)

**Comment by wimjongman** [comment]
Is it possible to check the "dismiss automatically" buttons? Now they are unchecked which leads to a confusing number of oomph screens around the eclipse ide:


![image](https://user-images.githubusercontent.com/180969/140522576-7af7b8b5-c2ec-4197-824c-a07a75bd6689.png)

**Comment by ruspl-afed** [comment]
@wimjongman  since we are talking about development environment I assume the "git" should be the default choice.

Ed @merks WDYT? Should we change defaut git protocol for setup? I don't see where one can change this in the script, and I do not know will it override user preferences or not.
The same for "Dismiss  automatically"
Please advice.

**Comment by wimjongman** [comment]
> 
> @wimjongman since we are talking about development environment I assume the "git" should be the default choice.

I think most people do not have ssh in place but use user/token combination. If they have ssh then they are savvy enough to select the git protocol.

**Comment by wimjongman** [comment]
It looks good to me! Very nice.

**Comment by wimjongman** [comment]
This one was fixed. Thanks all for pushing this. An important step forward.

Please use the new installer link and follow the instructions. The link is also available from the README.MD:

https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse/birt/master/build/org.eclipse.birt.releng/BIRTConfiguration.setup&show=true

**Comment by merks** [comment]
Note that I've made anonymous https the default in the combo box of clone URI choices.

The dismiss automatically is stored as a dialog setting and it is a different setting for the installer versus within the IDE so cannot be changed in the installer except by the user and is hard to change in the IDE where it typically doesn't matter because the perform (other than the very first time) runs in the background anyway.
