### ISSUE TITLE
genreport.bat in birt-runtime

### ISSUE THREAD

**Issue by colinsutton** [eclipse/birt#693]
Following the instructions in runtime_readme.txt
I set BIRT_HOME D:\BIRT\4.9\birt-runtime-4.9.0-20211105
I went to the ReportEngine directory
I ran 
   genreport.bat .\samples\hello_world.rptdesign -o helloworld.html
with the following output
   BIRT_HOME=D:\BIRT\4.9\birt-runtime-4.9.0-20211105\ReportEngine\\platform
   WORK_DIR=D:\BIRT\4.9\birt-runtime-4.9.0-20211105\ReportEngine\
   The input line is too long.
  The syntax of the command is incorrect.

It overwrote the BIRT_HOME!
I have no idea what it was trying to set the BIRTCLASSPATH to, resulting in that line too long.

The batch file should not set the BIRT_HOME
It should set BIRTCLASSPATH=%BIRT_HOME%\ReportEngine\lib\*

**Comment by wimjongman** [comment]
Thanks for reporting, Colin. Can you supply a patch to fix this?

**Comment by wimjongman** [comment]
> 
> 
> Thanks for reporting, Colin. Can you supply a patch to fix this?

With "patch", I mean in a pull request :)

**Comment by colinsutton** [comment]
I made the changes above and also the switch -d64 to the java command before it would run.
I can see there should be a platform directory...
D:\BIRT\4.9\birt-runtime-4.9.0-20211105>ReportEngine\genreport ReportEngine\samples\hello_world.rptdesign
gives the response:
"Error: Could not find or load main class ReportEngine\samples\hello_world.rptdesign"
but the file is there. 
My java is 1.8.0_311. Is that OK? The genreport in  BIRT 4.5 and 4.8 runtimes on the same computer both produce the correct html in the samples directory with the above command line.

**Comment by hvbtup** [comment]
> It should set BIRTCLASSPATH=%BIRT_HOME%\ReportEngine\lib*

Shouldn't that be

set BIRTCLASSPATH=%BIRT_HOME%\ReportEngine\lib\*

Note the additional backslash before the star.

Note: I never used genreport.bat, but at least this syntax would be similar to what our server does.

**Comment by hvbtup** [comment]
Maybe this issue is related to #781

**Comment by colinsutton** [comment]
Fixed in Fix report runner windows batch file #799 - thanks, Wim
