### ISSUE TITLE
Create launch configurations

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#698]
Provide an example configuration to launch tests from the workspace.

**Comment by wimjongman** [comment]
@patric_r can you test the new configurations, please?

**Comment by patric-r** [comment]
@wimjongman Thanks!
This works, 1603 tests had been executed.

-  I had to change java environment from java17 back to java11, maybe launch configuration should be changed in repo as well

- I wondered that all the tests had been completed within 6 seconds. That seems fast.
And I get exceptions at the console (while all tests are green). Is this expected?

- How many tests are part of this new "all model tests" suite? (rough percentage compared to all available tests)?
BTW, what are "models" in the eclipse/BIRT world?

- Just after starting the tests the following popup showed up:
![image](https://user-images.githubusercontent.com/10393382/141158659-a0ff7c6b-61a4-43ee-a418-e594ee838d64.png)

**Comment by wimjongman** [comment]
>     * I had to change java environment from java17 back to java11, maybe launch configuration should be changed in repo as well

Please make an issue and a pull request.

> 
>     * I wondered that all the tests had been completed within 6 seconds. That seems fast.
>       And I get exceptions at the console (while all tests are green). Is this expected?

Model tests are mostly in memory. Output is irrelevant as long as the tests are green. Failure testing is performed.

> 
>     * How many tests are part of this new "all model tests" suite? (rough percentage compared to all available tests)?

No idea, 10%?

>       BTW, what are "models" in the eclipse/BIRT world?

The ROM: https://www.eclipse.org/birt/documentation/reference.php
