### ISSUE TITLE
Replace deprecated Navigator with Project Explorer in Report Design perspective

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#710]
The report design perspective uses the Navigator but it is deprecated. Use the Project Explorer instead.

This can be fixed in the ReportPerspective class.

**Comment by qs-wang** [comment]
Interesting after leaving for such a long time, BIRT is still using navigator which I added. Let me try to fix it then. ^_^

**Comment by claesrosell** [comment]
@qs-wang how far is you with this? I saw this comment just now. I have been worked on a PR for this on "after hours" for a couple of days. I was just about to commit it.

**Comment by qs-wang** [comment]
> @qs-wang how far are you with this? I saw this comment just now. I have been worked on a PR for this on "after hours" for a couple of days. I was just about to commit it.

ah, ok. I haven't really started yet. I'll look around, and may try other items later on.
