### ISSUE TITLE
UI displays wrong page protect property 

### ISSUE THREAD

**Issue by hvbtup** [eclipse/birt#718]
This is number 2 in my personal list of annoying issues with BIRT 4.2.1 - I don't know if this is already fixed in the source.

I don't know which property exactly is displayed incorrectly (so I hope others know this issue as well and can provide more details).

Getting page breaking right is always one of the main problems when developing reports (regardless of the tool). So during the last phase of development / debugging I use to test the page-breaking behavior and fine-tune it.

Sometimes, I just can't see why the page-breaking behaves different from what I expect after very carefully looking at the page-breaking properties of each report item in the UI. Most of the times, the reason is the person sitting in front of the screen...

But sometimes it is this bug:

The UI shows a different value than what is actually specified in the .rptdesign XML.
IIRC the display shows "Avoid" but this is not specified in the XML (or similar - unfortunately I don't have an example at hand).

**Comment by wimjongman** [comment]
Can you test this against the daily snapshot? See the main [README.md](https://github.com/eclipse/birt/blob/master/README.md) for the location of the download

**Comment by wimjongman** [comment]
> Most of the times, the reason is the person sitting in front of the screen...

:)

> The UI shows a different value than what is actually specified in the .rptdesign XML.
> IIRC the display shows "Avoid" but this is not specified in the XML (or similar - unfortunately I don't have an example at hand).

We really need to have an example. As soon as you catch it, please post an example.

**Comment by hvbtup** [comment]
Tested this in the Oomph-generated eclipse.
I just created a report with an empty 10x10 grid, then select the top-left cell, then all cells in the first column (with 9x shift-down) and then the rest of the cells with 9x shift-right. On a CORE i5-3470 it takes 26 seconds to select all 100 cells.
It is more fun with the outline view opened :-)

**Comment by hvbtup** [comment]
> Tested this in the Oomph-generated eclipse.
> I just created a report with an empty 10x10 grid, then select the top-left cell, then all cells in the first column (with 9x shift-down) and then the rest of the cells with 9x shift-right. On a CORE i5-3470 it takes 26 seconds to select all 100 cells.
> It is more fun with the outline view opened :-)

Sorry, wrong issue!

**Comment by hvbtup** [comment]
It was about the page-break-inside property of groups. The UI shows avoid but the XML contains auto.

I created a test report using classic models Products table
```
select *
from products
order by productline, productcode

``` 
and a table item with a group based on productline.

In 4.2.1 the UI shows page break inside: Avoid

![grafik](https://user-images.githubusercontent.com/7644776/142395450-cf5b36d5-bdff-4e43-8f4a-a8cb65d48988.png)

which is wrong because that is not the default and is not contained in the XML:

```
            <group id="34">
                <property name="groupName">ProductLine</property>
                <expression name="keyExpr" type="javascript">row["PRODUCTLINE"]</expression>
                <structure name="toc">
                    <expression name="expressionValue" type="javascript">row["PRODUCTLINE"]</expression>
                </structure>
                <property name="hideDetail">false</property>
                <header>
```

And in the PDF layout, the group e.g. "Trucks and Buses" looks like
![grafik](https://user-images.githubusercontent.com/7644776/142395921-bc269e1a-1ff8-4736-8159-0e66af86b60d.png)

The bug seems to be fixed, because with the Oomph generated eclipse, this is correctly shown as:
![grafik](https://user-images.githubusercontent.com/7644776/142396092-22eb87bc-2278-4a8d-a72b-40902056cf4b.png)

Sorry for opening this as an issue. I didn't find this mentioned in the old bug list or by looking through the GIT commits.

Good to know this is already solved.

**Comment by wimjongman** [comment]
Now it is documented. 👍
