### ISSUE TITLE
Build for multiple targets 

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#729]
We should also build for mac and linux. At the moment we only build for windows.

The following needs to be added to the pom somewhere:

		<environment>
			<os>linux</os>
			<ws>gtk</ws>
			<arch>x86_64</arch>
		</environment>
		<environment>
			<os>macosx</os>
			<ws>cocoa</ws>
			<arch>x86_64</arch>
		</environment>

**Comment by wimjongman** [comment]
Alexander, can you fix this?

**Comment by ruspl-afed** [comment]
I think this one is done by @claesrosell
