### ISSUE TITLE
Archive build artifacts

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#730]
We can archive build artifacts with github actions. In this way, we can make executables available after every pull request for people to test.

https://github.com/actions/upload-artifact

we can archive the whole workspace or selected targets in the build directory.

**Comment by wimjongman** [comment]
@ruspl-afed Alexander, something for you?

**Comment by claesrosell** [comment]
I would like to try this out. I have never worked with GitHub CI and Actions but would like to learn about it.

**Comment by claesrosell** [comment]
It does not seem like I am allowed to push workflow changes. I will need to look into why later.

@wimjongman I know that you have made changes to the workflow earlier, if you would like to look at what I have done, here is the ci.yml file:

[ci.yml.txt](https://github.com/eclipse/birt/files/7604916/ci.yml.txt)

**Comment by wimjongman** [comment]
> It does not seem like I am allowed to push workflow changes. I will need to look into why later.

Only project members can do this. There is a security risk to receive workflow changes from the outside because.

> 
> @wimjongman I know that you have made changes to the workflow earlier, if you would like to look at what I have done, here is the ci.yml file (totally untested):
> 

Looks great. I will create a branch.

**Comment by wimjongman** [comment]
> I would like to try this out. I have never worked with GitHub CI and Actions but would like to learn about it.

Who said that nobody makes the first jump? https://github.com/eclipse/birt/actions/runs/1505140952
