### ISSUE TITLE
org.eclipse.birt.report.designer.internal.ui.editors.script.JSEditor is leaking Fonts

### ISSUE THREAD

**Issue by claesrosell** [eclipse/birt#734]
JSEditor.setDescriptionText(String text) is creating a new Font on every call.

```
private void setDescriptionText(String text) {
	Font font = descriptionText.getFont();
	FontData[] fontData = font.getFontData();
	....
	descriptionText.setFont(new Font(font.getDevice(), fontData));
	descriptionText.setText(description);
}
```
We should probably use BIRTS FontManager or the backing JFaceResources.getFontRegistry() directly instead.

**Comment by wimjongman** [comment]
Yes. good catch. In this case, something like this can also work.


      Font font = new Font(font.getDevice(), fontData)
      descriptionText.setFont(font);
      descriptionText.addListner(SWT.Dispose, e-> font.dispose());
