### ISSUE TITLE
"Orbit latest" updated, missing dependencies in target platform

### ISSUE THREAD

**Issue by claesrosell** [eclipse/birt#741]
"Orbit latest" updated yesterday and some of our dependencies does not exist anymore. Build fails in my environment, which honestly is a work in progress. This issue is for tracking which changes that needs to be done.

**Comment by wimjongman** [comment]
Sorry to steal this from you, Claes. I needed it.

**Comment by patric-r** [comment]
@wimjongman thanks, but the Oomph installer is still failing with "Unable to locate installable unit org.apache.commons.compress 1.20.0.v20210713-1928"

**Comment by wimjongman** [comment]
If you are pulling from your own repository then you have to rebase first (or throw it away and fork it again).

**Comment by patric-r** [comment]
Oh dear, you're right, it was late yesterday - thanks.

**Comment by wimjongman** [comment]
You can do "fetch upstream" in Github UI. After you pull locally and restart, the installer should recover.
