### ISSUE TITLE
Fix report runner windows batch file

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#799]
This batch file will not resolve the classpath correctly and also does not know about the OSGi runtime.

**Comment by colinsutton** [comment]
pdf output produces the correct result but gives a warning:
D:\BIRT\4.9\birt-runtime-4.9.0-20220201\ReportEngine>genreport.bat -p "sample=This is the value of the test parameter" -f pdf .\samples\hello_world.rptdesign
OSGI-Mode, BIRT_HOME=D:\BIRT\4.9\birt-runtime
Java command=java -cp "D:\BIRT\4.9\birt-runtime-4.9.0-20220201\ReportEngine\lib\*" -DBIRT_HOME=D:\BIRT\4.9\birt-runtime org.eclipse.birt.report.engine.api.ReportRunner -p "sample=This is the value of the test parameter" -f pdf .\samples\hello_world.rptdesign
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.lowagie.text.pdf.MappedRandomAccessFile$1 (file:/D:/BIRT/4.9/birt-runtime-4.9.0-20220201/ReportEngine/lib/com.lowagie.text_2.1.7.v201004222200.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.lowagie.text.pdf.MappedRandomAccessFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by colinsutton** [comment]
Also fixes:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=473450
https://bugs.eclipse.org/bugs/show_bug.cgi?id=484453
https://bugs.eclipse.org/bugs/show_bug.cgi?id=547526
I will close them when BIRT is released.
