### ISSUE TITLE
Embedded libraries

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#802]
We have the following embedded libraries in the repository (excluding the jars in tests). 

For the release we need to figure out if we've got any license or security issues with these. 

"birt\build\org.eclipse.birt.build\lib\dom4j-1.6.1.jar"
"birt\chart\org.eclipse.birt.chart.device.pdf\lib\fop-2.6.jar"
"birt\common\org.apache.axis\lib\axis-1.4.1-SNAPSHOT.jar"
"birt\common\org.apache.axis\lib\axis-1.4.1-SNAPSHOT-sources.jar"
"birt\common\org.apache.axis\lib\axis-ant.jar"
"birt\common\org.w3c.sac\lib\flute.jar"
"birt\data\org.eclipse.birt.me.prettyprint.hector\lib\cassandra-thrift-1.1.0.jar"
"birt\data\org.eclipse.birt.me.prettyprint.hector\lib\commons-lang-2.4.jar"
"birt\data\org.eclipse.birt.me.prettyprint.hector\lib\guava-r09.jar"
"birt\data\org.eclipse.birt.me.prettyprint.hector\lib\hector-core-1.1-2.jar"
"birt\data\org.eclipse.birt.me.prettyprint.hector\lib\libthrift-0.14.0.jar"
"birt\data\org.eclipse.birt.me.prettyprint.hector\lib\slf4j-api-1.6.1.jar"
"birt\data\org.eclipse.birt.me.prettyprint.hector\lib\slf4j-nop-1.6.1.jar"
"birt\engine\org.eclipse.birt.report.engine\lib\commons-cli-1.0.jar"
"birt\engine\org.eclipse.birt.report.engine\lib\Tidy.jar"
"birt\engine\uk.co.spudsoft.birt.emitters.excel\lib\commons-codec-1.5.jar"
"birt\model\org.eclipse.birt.report.model.adapter.oda\lib\odadesignapi.jar"
"birt\common\org.apache.derby.core\derby.jar"

**Comment by ruspl-afed** [comment]
@wimjongman do you think we need to switch to maven dependencies where possible?

**Comment by wimjongman** [comment]
Yes, where possible we should absolutely do it. I think the libraries are needed to build the runtime and the web application. 

There is a bundle org.eclipse.birt.build that contains additional build scripts. I think maven calls them at some point but I don't know how.

**Comment by claesrosell** [comment]
I think that:

"birt\viewer\org.eclipse.birt.report.viewer\birt\WEB-INF\lib\jsp.jar"
"birt\viewer\org.eclipse.birt.report.viewer\birt\WEB-INF\lib\viewservlets.jar"

... are created during build from our sources and can be excluded from the list.

**Comment by wimjongman** [comment]
you are correct, I have removed them from the main comment.

**Comment by wimjongman** [comment]
@waynebeaton Wayne, can you advise on the best way to proceed?

**Comment by waynebeaton** [comment]
I believe that these are all good-to-go from an IP due diligence point of view (notwithstanding the question below). I've mapped them to what I hope are the correct Maven GAVs.

Many of these are *very* old. There may be opportunities to tighten up from a security POV.

- dom4j:dom4j:1.6.1 (DOM4J)
- org.apache.xmlgraphics:fop:2.6 (Apache-2.0)
- org.apache.axis:axis:1.4.1 (Apache-2.0)
- org.apache.axis:axis-ant:1.4.1 (Apache-2.0)
- org.w3c.sac:flute:1.3 (Apache-2.0)
- org.apache.cassandra:cassandra-thrift:1.1.0 (Apache-2.0)
- commons-lang:commons-lang:2.4 (Apache-2.0)
- com.google.guava:guava:r09 (Apache-2.0)
- org.hectorclient:hector-core:1.1-2 (MIT)
- org.apache.thrift:libthrift:0.14.0 (Apache-2.0)
- org.slf4j:slf4j-api:1.6.1 (MIT)
- org.slf4j:slf4j-nop:1.6.1 (MIT)
- commons-cli:commons-cli:1.0 (Apache-1.1)
- net.sf.jtidy:jtidy:r938 (JTidy)
- commons-codec:commons-codec:1.5 (Apache-2.0)
- org.apache.derby:derby:10.8.2.2 (Apache-2.0)

Our existing automated tools don't pick these up. I'll see what I can do to address this. The next generation stuff that we're working on (more to come on this shortly, I hope) should be able to at least find these as part of the IP review.

I don't know what this is. Is this project code? Is it something else?

- "birt\model\org.eclipse.birt.report.model.adapter.oda\lib\odadesignapi.jar"

If you're not sure, maybe check to see if there is any Maven information embedded in the JAR.
