### ISSUE TITLE
BIRT OSGi startup: java.lang.UnsupportedOperationException: Not able to create StateObjectFactory implementation

### ISSUE THREAD

**Issue by blatra** [eclipse/birt#835]
Hello Team,

when I start the BIRT Platform using `Platform.startup (engineConfig);` the following error comes up in the log hundreds of times:

> ERROR [stderr] (Start Level: Equinox Container: 5e58e5a4-451b-49b1-bee8-0c6462d606dc) Error Processing: org.eclipse.equinox.internal.p2.extensionlocation.SiteListener@74bf1f63: java.lang.UnsupportedOperationException: Not able to create StateObjectFactory implementation: org.eclipse.osgi.internal.resolver.StateObjectFactoryImpl

But it seems that BIRT itself operates without issues afterwards, but I'm not 100% sure.

I'm using the BIRT 4.8 Runtime OSGi on Wildfly 20 with OpenJDK JDK 1.8.0_212.
I already tried to run it on AdoptOpenJDK jdk8u252-b09, but this did not solve the issue.
I did not try later java 8 update versions because of #660.

I've seen that this error is mentioned in [eclipse bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=547526#c1) as well as in [issue 787](https://github.com/eclipse/birt/issues/787#issuecomment-1020224458).

Do you know what causes the error and if it can be fixed?
Or maybe there is a way to suppress this error messages (in the case it does not break BIRTs functionality) - maybe via some configuration in config.ini?

Thank you in advance for your help.

**Comment by hvbtup** [comment]
As this also happens with the GitHub master branch (which will be BIRT 4.9.0 soon) - see comments in #787 - I changed the title.

**Comment by blatra** [comment]
Unfortunally this did not solve the problem.
I did also try to add a folder "features" on the same level (because I had a look at the SiteListener Sources), but without luck:

```
ReportEngine
├── lib
├── platform
│   ├── configuration
│   ├── dropins
│   ├── features
│   ├── p2
│   ├── plugins
│   └── workspace
└── samples
```

Sadly, the error message does not contain any line numbers and I'm not able to identify the relevant line in SiteListener sourcecode.

Is there a way to get a more verbose output or maybe a complete stacktrace inside the log?
It should be possible to find out which code actually throws the "UnsupportedOperationException", right?

**Comment by wimjongman** [comment]
Ah, thanks for trying. Maybe @tjwatson knows directly what is going on when he looks at:

ERROR [stderr] (Start Level: Equinox Container: 5e58e5a4-451b-49b1-bee8-0c6462d606dc) Error Processing: org.eclipse.equinox.internal.p2.extensionlocation.SiteListener@74bf1f63: java.lang.UnsupportedOperationException: Not able to create StateObjectFactory implementation: org.eclipse.osgi.internal.resolver.StateObjectFactoryImpl

**Comment by tjwatson** [comment]
This error happens if you do not have the framework extension `org.eclipse.osgi.compatibility.state`

**Comment by blatra** [comment]
That's it.

I've successfully removed the error message at startup.

What I did was to ...

1. download the mentioned artifact from [maven central](https://search.maven.org/remotecontent?filepath=org/eclipse/platform/org.eclipse.osgi.compatibility.state/1.2.500/org.eclipse.osgi.compatibility.state-1.2.500.jar) and place it underneath the "platform/plugins" folder
2. edit the file "platform/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info" and to add this line to the end of the file:
`org.eclipse.osgi.compatibility.state,1.2.500.v20210730-0750,plugins/org.eclipse.osgi.compatibility.state-1.2.500.jar,4,false`

Afterwards the error does not come up anymore when the platform is started.

**Comment by blatra** [comment]
Thank you very much for your support.

I guess `org.eclipse.osgi.compatibility.state` will be added to the next official BIRT OSGi release, right?

**Comment by wimjongman** [comment]
It will most certainly be if you create a pull request with the change. 🙏

**Comment by wimjongman** [comment]
Yes, I too am puzzled by the ant stuff. If possible, that should just go away and be replaced by a product configuration.

The ant stuff does seem to pull in mostly recent jars, although the runtimes contain some old stuff as well.
