### ISSUE TITLE
Aggregation button disabled

### ISSUE THREAD

**Issue by jochenberger** [eclipse/birt#856]
Hi,

we tried to upgrade to 4.9. The results look very promising (:clinking_glasses:), but it looks as if there is still an issue with the aggregation button. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=511212 for reference.

Cheers,
Jochen

_Originally posted by @jochenberger in https://github.com/eclipse/birt/discussions/855_

**Comment by claesrosell** [comment]
I have made a fix for this, that is building now. The build will be available here: https://github.com/eclipse/birt/actions/runs/1959493255
Please try it out.

**Comment by jochenberger** [comment]
@claesrosell, the fix works for us. Thanks for the quick action.

**Comment by speckyspooky** [comment]
@claesrosell 
I tested the original-report with rcp-version-4.9 and confirm too. The fix works and the function editor is now usable.
Thanks to your side!

![rcp-designer-4 9](https://user-images.githubusercontent.com/41593722/157748968-e470cb53-a5fe-484a-85f0-31f9303dac56.png)

**Comment by wimjongman** [comment]
Thanks, Claes. Another quality patch.
