### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#874]
We have a load of branches. Many of them are years old and are behind AND ahead of master. I suggest we snip them.

**Comment by hvbtup** [comment]
+1

**Comment by wimjongman** [comment]
@TheLaserNinja  can you take care of this?

**Comment by TheLaserNinja** [comment]
Hey Wim,

Sure, what needs to be done?

-John

On 2022-09-19 09:32, Wim Jongman wrote:

> @TheLaserNinja [1] can you take care of this?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/TheLaserNinja
[2] https://github.com/eclipse/birt/issues/874#issuecomment-1251107160
[3]

**Comment by wimjongman** [comment]
Any progress here?

**Comment by TheLaserNinja** [comment]
How far back would you like the branches cleaned? I know there were 
still some products that used versions as old as 3.7. Should we archive 
these before removing them?

-John

On 2022-09-27 07:32, Wim Jongman wrote:

> Any progress here?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/eclipse/birt/issues/874#issuecomment-1259439268
[2]

**Comment by wimjongman** [comment]
Do we have to archive? The full history is always available in Git. People can branch off of a specific commit at their will.

Note to that to build BIRT 3.7, people also have to have access to all the old dependencies from 10 years ago :)

Maybe you can make a fork and stash that somewhere (e.g. on a wiki page) just be on the save side.

**Comment by wimjongman** [comment]
I suggest snipping all the old branches.

**Comment by wimjongman** [comment]
No reaction so I removed all stale branches
