### ISSUE TITLE
Report with Oracle JDBC ORA-01000 Too many open cursors

### ISSUE THREAD

**Issue by hvbtup** [eclipse/birt#875]
We are facing a serious issue with BIRT 4.9 when used with an Oracle DB.

One of our reports has a structure like this:
![grafik](https://user-images.githubusercontent.com/7644776/158799538-b8648320-5fd3-4b65-8f62-306767af6faa.png)
That is, we have a simple master-detail structure (with multiple details).

The table "Reports" is bound to a JDBC dataset with the same name.
For each report, there are some detail tables, one of these is table "Ausgabegeräte", which is bound to a JDBC dataset with the name.
Some systems call this a "sub-report".

The dataset "Ausgabegeräte" uses a dataset parameter to select the detail data for the given report from the layout context (DataSet Parameter Binding)
![grafik](https://user-images.githubusercontent.com/7644776/158800061-2ec3619b-9931-4623-bb1e-190b3eb8a5e7.png)

The datasets contain beforeOpen events just for debugging and performance tuning purposes (showing that the dataSet is about to opened for a given REPT_ID).

This is all very straightforward und it worked for > 10 years.

But now, with BIRT 4.9, the report crashes with "ORA-01000 too many open cursors" error message in the exception trace
if I restrict
By using Oracle's tracing tools, I could verify that indeed the cursors for the SQL statements in the reports' datasets are closed only at the end of the report instead of when the processing is done.

I added logging statements to the `afterOpen` and `afterClose` events of the dataset "Ausgabegeräte" and this explains the error:

With BIRT 4.3, the sequence of the events was

     afterOpen afterClose
     afterOpen afterClose
     afterOpen afterClose
     ...

but with BIRT 4.9 the sequence is 

    afterOpen afterOpen afterOpen ...
    afterClose afterClose afterClose

**So, the JDBC cursors are freed only at the end of the whole report. It seems like something has changed significantly in the processing.**

Maybe something has changed regarding caching (or options have been renamed or have different default values?)

Note: The report uses `RunAndRenderTask`.

**Comment by claesrosell** [comment]
@hvbtup. Can you try tro reproduce this behavior with a small example report and the sample data base? That way I could look into without much effort. Time is really limited right now.

**Comment by hvbtup** [comment]
I created a sample reporting demonstrating the different behavior.
[issue-875.zip](https://github.com/eclipse/birt/files/8286156/issue-875.zip)

Both log files were created by running the report directly in the all-in-one designer and then renaming the file.

**Comment by hvbtup** [comment]
I created the report with the ClassicCars sample DB. Seems like the afterClose isn't called at all. 
My assumption for BIRT 4.9 that `afterClose` is called too late seems to be wrong:  It seems like if it isn't called at all.

**Comment by hvbtup** [comment]
I tested with BIRT 4.4.2 and BIRT 4.8.0 - no issue.
BIRT 4.9.0 is still downloading from the Eclipse download site. This is sooo slow in comparison to GH.

Meanwhile, I am looking at commits sind 2019-05-20.

My first suspect commit is b86b5466030b8e9b684a8fec17081316f19580c0 where a line queryService.close( ); was removed.

**Comment by hvbtup** [comment]
Confirmed the changed behavior with the new official 4.9.0 all-in-one designer.
The suspect commit is still the only one. I'll try what happens if I rever it.
@meeta09 can you provide more information about the issue that you tried to fix with https://github.com/eclipse/birt/commit/b86b5466030b8e9b684a8fec17081316f19580c0 ? Maybe a different solution for that issue is possible?

**Comment by claesrosell** [comment]
I think that it was this one:
https://forums.opentext.com/forums/developer/discussion/299258/get-page-count-failed-appeared-when-trying-to-move-to-next-page

**Comment by hvbtup** [comment]
Hmm... ATM I can't build and run the all-in-one anymore (!?), so I cannot check if reverting that commit would help.

**Comment by claesrosell** [comment]
Is it something with your fork or something else?
If it is your target platform that causes the build issues: The integration repository of Eclipse 4.23 was removed yesterday either switch 4.23-i  to 4.23 or 4.24-i in the .target file.

**Comment by claesrosell** [comment]
I made a PR which reintroduced the call to .close(). I have not tested it, but there should be testable builds soon.

**Comment by hvbtup** [comment]
I tested it with issue-875.rptdesign and now the afterClose event is called again :smiley:.

I have not yet tested the fix with application-specific Oracle JDBC report, but I'm pretty sure this will solve the issue - I'll give feedback.

The to-be-reverted commit b86b5466030b8e9b684a8fec17081316f19580c0 comment says 

> Fix to resolve the "Get page count failed" error caused while running a report with chart that is based on Join DS from datadesign

It is clear that the commit caused different behavior from what is specified and documented.

As a temporary workaround, I'll use your PR in the tup_main branch of our fork in order to avoid this issue in our product.
We don't use Join Datasets anyway, so that commit fixed something that was never a problem for us.

But for eclipse/birt, I fear that the solution might not be that simple.
I mean, the commit is there to fix an issue for a different usage scenario, so we can hardly just ignore and revert it.
The commit seems to be a rather dirty hack for the issue described in https://forums.opentext.com/forums/developer/discussion/299258/get-page-count-failed-appeared-when-trying-to-move-to-next-page - maybe a different solution is possible?

A relatively simple solution would be to introduce an option to choose at runtime if queryService.close( ) should be called or not.
Then we would have to decide about 
1) where to specify this option and 
2) what the default value should be.

For the first question, it could be set at the Task level or at the report level or both.
From my POV it should suffice to set it at the Task level. Then we wouldn't have to change the ROM.

I'm biased regarding the second question of course: The default value should be "yes, close the connection" (as it was until BIRT <= 4.8.0). because a report with a lot of dataset executions seems much more common (from my point of view) than a timeout issue in a report using Join datasets. Join datasets are AFAIK necessary *only* if a report mixes data from 2 or more data sources, which is a small minority of reports, I think.

**Comment by claesrosell** [comment]
My 5 cents.
The commited "patch" for the issue described in the forum patch is wrong. The solution to that problem is not to skip closing resources, in this case ultimately: resultsets / database cursors. That .close() method was not called from any place in birt after its removal.

What probably should happen is that if a transient .rptdocument is missing it should be recognized by the caller and it should re-generate the document. An easier/less robust solution would be to increase the "alive time" of the report.
Both those solutions would probably be in code which packages start with: com.actuate.

**Comment by hvbtup** [comment]
@claesrosell  That sounds absolutely reasonable. 
I just want to avoid the impression that we simply ignore the work done by OpenText...
However, in this case the patch to fix something there just broke something here, so it's up to OpenText to find a different solution.

**Comment by wimjongman** [comment]
I agree. Let's revert that patch.

**Comment by hvbtup** [comment]
I can confirm that #876 solves the issue with the Oracle JDBC report (as expected).
