### ISSUE TITLE
Please, export the repository for the rcp-designer also.

### ISSUE THREAD

**Issue by UrsZeidler** [eclipse/birt#879]
We are in the unfortunate position that we reuse the _org.eclipse.birt.report.designer.ui.rcp.DesignerApplication_ in our internal Report-Designer so we depend on the bundel _org.eclipse.birt.report.designer.ui.rcp_ which is not part of the normal update site: https://download.eclipse.org/birt/update-site/4.9.0/
The Designer product is currently only available as product export in https://download.eclipse.org/birt/downloads/drops/R-R1-4.9.0-202203161719 
Could you bring the corresponding updatesites also online? (birt-packages/birt-report-rcp)

Thanks.

**Comment by wimjongman** [comment]
Thanks for the report, Urs. How did you consume this bundle earlier?

**Comment by UrsZeidler** [comment]
At the beginning there was only a directory. (3.7) ...
Now with maven and tycho we use _https://ci.eclipse.org/birt/job/birt-master/204/artifact/build/birt-packages/birt-report-rcp/target/repository/_
prior to your release we used the base master build: _https://ci.eclipse.org/birt/job/birt-master/lastSuccessfulBuild/artifact/build/birt-packages/birt-report-rcp/target/repository/_ in conjunction with _https://download.eclipse.org/birt/update-site/snapshot/_

greetings Urs.

**Comment by wimjongman** [comment]
Thanks! I see that was never officially deployed. Would it work for you if we deploy that repository as a zip file?

**Comment by UrsZeidler** [comment]
It would be better as to create the update site from the product zip, via p2 magic, but it would not be as smooth as a simple updatesite in the target platform.
So yes and no.

greetings, Urs.

**Comment by wimjongman** [comment]
The problem I have with adding this to the update site is that users will install it because they normally don't know what all this means.  So we would have to create an "Extra" feature containing the loose bundles.

Do you have a suggestion on how to solve this?

**Comment by UrsZeidler** [comment]
I totally agree on this, no one wants and should install this bundle in their ide.
There is already a feature containing this bundle: _org.eclipse.birt.rcp_ in  (features/org.eclipse.birt.rcp.feature) and used - for example - in the birt-packages/birt-report-rcp/BIRT.product.
If you could add this feature to the default updatesite (/org.eclipse.birt.build-parent/org.eclipse.birt.p2updatesite/) 
In the BirtNL category the corresponding _org.eclipse.birt.rcp.nl_ is already there. 

Maybe a simple hint, -don't install in the ide- would be sufficient. other runtime bundels use a similar approach.

greetings.

**Comment by wimjongman** [comment]
@UrsZeidler If you want to have this, I am happy to review and accept your PR.

**Comment by wimjongman** [comment]
Thanks @UrsZeidler
