### ISSUE TITLE
SimpleResultSet.groupCalculator() called for index(0) even if the RowResultSet is empty

### ISSUE THREAD

**Issue by claesrosell** [eclipse/birt#922]
The group calculator and hence the aggregator function is called even on empty result sets, this leads to erroneous results for certain aggregator functions, like COUNT.

**Comment by hvbtup** [comment]
Old pages which describe the behavior:

https://www.eclipse.org/forums/index.php/t/848630/
Aggregation Count returns "1" when 0 row returned

https://bugs.eclipse.org/bugs/show_bug.cgi?id=438257 Visibility expression on table based on COUNT aggregate not working since BIRT 4.3.0
