### ISSUE TITLE
Maven Central Repository availability

### ISSUE THREAD

**Issue by AlexSchuetz** [eclipse/birt#936]
I am wondering why the dependencies are not available over maven central.

4.6 is the latest runtime I can find. Am I missing something?

Why was poblishing to maven central stopped? Are there plans to publish to maven central in future? Or is another repository used?

**Comment by claesrosell** [comment]
Eventually, it will be published to Maven. The efforts to do so can be tracked here: https://github.com/eclipse/birt/issues/625
