### ISSUE TITLE
WebViewer does not work from Eclipse IDE on Linux

### ISSUE THREAD

**Issue by claesrosell** [eclipse/birt#943]
When I run master on my Linux machine I get this error when I am using the web viewer
`HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: File [/webcontent/birt/pages/layout/FramesetFragment.jsp] not found`

This error is similar to #935 and #915 and can be related even if those issues are experienced from build versions of Birt.

The problem boils down to that a non-canonical path to the .jsp page is considered an alias by Jetty. The path is then rejected since none of the available org.eclipse.jetty.server.handler.AliasCheck.check() calls accepts it.

**Comment by wimjongman** [comment]
Claes, you are the master. Great catch! Thank you.
