### ISSUE TITLE
BIRT 4.9.0 runtime in maven repo

### ISSUE THREAD

**Issue by rajn** [eclipse/birt#949]
Hi,

We want to use BIRT 4.9.0 runtime in our application. Wanted to know when we can expect it in maven repo. The last one we see is following dated Nov 2016.

    groupId - org.eclipse.birt.runtime
    artifactId - org.eclipse.birt.runtime
    version - 4.6.0-20160607

thanks in advance,
raj

**Comment by claesrosell** [comment]
Eventually, it will be published to Maven. The efforts to do so can be tracked here: https://github.com/eclipse/birt/issues/625
