### ISSUE TITLE
Version of justj should be 0.0.0 in target file

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt#982]
The build fails because:

[ERROR] Failed to resolve target definition C:\Users\hvb\birt-master\git\birt\build\org.eclipse.birt.target\org.eclipse.birt.target.target: Could not find "org.eclipse.justj.openjdk.hotspot.jre.full.feature.group/11.0.14.v20220314-1349" in the repositories of the current location -> [Help 1]

_Originally posted by @hvbtup in https://github.com/eclipse/birt/issues/923#issuecomment-1136054864_

**Comment by wimjongman** [comment]
Claes, can you please wait with the commit, I am using this issue for a demo at IBM PowerUp 2022.

**Comment by claesrosell** [comment]
Sure.
I have a PR building right now. Should I delete it?

**Comment by wimjongman** [comment]
No that is fine, it is actually a good example of what I want to communicate.
