### ISSUE TITLE
Local build fails because orbit latest changes

### ISSUE THREAD

**Issue by SteveSchafer-Innovent** [eclipse/birt#988]
I find that my local build fails because https://download.eclipse.org/tools/orbit/downloads/latest-R changes and referenced artifacts either change version or disappear entirely (e.g. javax.xml.stream is missing from https://download.eclipse.org/tools/orbit/downloads/drops/R20220531185310/, which is the current "latest").

Can we instead refer to an explicit orbit build id in the target file?

**Comment by wimjongman** [comment]
Got your back brother. Solved with https://github.com/eclipse/birt/pull/987
